# Question 1

Write a program that will find all numbers which are divisible by 7 but are not a multiple of 5, between 2000 and 3200 (both included). The numbers obtained should be printed in a list.

Hints: Consider using the range(#begin, #end) method.


In [54]:
# n betwenn 2000 and 3200 both
import numpy as np
def NUMBER():
    arr = []
    for n in range(2000,3001,1):
        if n%7 ==0:
            if n%5 !=0:
                arr.append(n)
    return list(np.array(arr).T)

print(NUMBER())

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996]


#  Question 2 

 Write a program that can compute the factorial of a given number. (the factorial of n is the product of all positive integers less than or equal to n). for example factorial(5)= 5 x 4 x 3 x 2 x 1 the result is 120.  (i.e. factorial (0)=1)



In [53]:
# compute the factorial of a given number
# given Number muss be Positive/ fac(0)=1

# factorial Function

def fact(n):
    if n<0:
        return print("factorial not possible")
    elif n ==0:
        N = 1
        return N
    else:
        N =1
        for i in range(1,n+1,1):
            N = i*N    
    return N



# Check if the Input is Int, if not (Char or float) ty again!!
def Checkifint():
    it_is = False
    while it_is == False:
        Number = input("Given Nummer: ")
        
        try: 
            #Check if it's Float 
            if float(Number) == 0.0:
                print()
            elif (float(Number) > 0.0 and float(Number) <1.0) or (float(Number) > -1.0  and float(Number) < 0.0):
                # produce errors to jump into the except
                int("produce errors")
            elif  float(Number)% int(float(Number)) != 0 :
                # produce errors to jump into the except
                int("produce errors")
            int(float(Number))
            it_is = True
        except ValueError :
            it_is = False
            # try to input an integer
            print("The Given Number is not an integer, Please give an integer:")
    return int(float(Number))


# compute the factorial
fact(Checkifint())

Given Nummer: d
The Given Number is not an integer, Please give an integer:
Given Nummer: 5


120

# Question 3 

With a given integer number n, write a program to generate a dictionary that contains (i, i*i) such that is an integral number between 1 and n (both included). and then the program should print the dictionary. Suppose the following input is supplied to the program: 8 Then, the output should be: {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}  


In [55]:
# input number 
# compute dict

def dict(p):
    MyDict = {}
    for i in range(1,n+1,1):
        MyDict[i] = i*i
    return MyDict

n = int(input("Giv a Nummber: "))
print(dict(n))

Giv a Nummber: 8
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


# Question 4 

Given a non-empty string and an int n, return a new string where the char at index n has been removed. The value of n will be a valid index of a char in the original string (i.e. n will be in the range 0..len(str)-1 inclusive). 

missing_char('kitten', 1) → 'ktten'    for example here we remove "i" which is located in the index 1

missing_char('kitten', 0) → 'itten'   here we remove "k" which is in the index 0

missing_char('kitten', 4) → 'kittn'   here we remove "e" which is in the index 4

In [33]:
# Give a non/empty String Str

# Str = input("Give a non/empty String: ")



# Check if Given String Str empty is?

def Checkifempty():
    Str = ""
    while not len(Str):
        Str = input("Give a non/empty String: ")
    return Str



# Check if input int is ?  + Check if n is a Valid index n of a Char in range 0..len(str)-1 

def Checkifint():
    it_is = False 
    while it_is == False:
        n = input("Give a Valid index n: ")
        try:
            int(n)
            it_is = True
            if int(n) >= len(Str) or int(n) < 0 :
                print("Invalid Number, Please try again and enter a Valid index: ")
                 # produce errors to jump into the except
                int("a")                 

# invalid/if not int, try again 

        except ValueError : 
            it_is = False
    
    return int(n)

# Romove char with Index n in a Given String Str 

Str = Checkifempty()
n = Checkifint()

Str =Str[:n] + Str[n+1:len(Str)]
print(Str)

Give a non/empty String: 
Give a non/empty String: Hello
Give a Valid index n: 19999
Invalid Number, Please try again and enter a Valid index: 
Give a Valid index n: 2
Helo


# Question 5 

Write a NumPy program to convert a NumPy array into a Python list structure.

Expected Output: 

Original array elements: [[0 1] [2 3] [4 5]] 

Array to list: [[0, 1], [2, 3], [4, 5]] 
 

Hint: we can use the to_list() function to ensure the conversion.

In [41]:
# convert a NumPy array into a Python list structure
import numpy as np

arr = np.random.randint(3,19,size=(3,4))
print(f'NumPy Array:\n{arr}')

print(f'List: {arr.tolist()}')

NumPy Array:
[[18 17 14 16]
 [10 12 17  3]
 [10 17 14  4]]
List: [[18, 17, 14, 16], [10, 12, 17, 3], [10, 17, 14, 4]]


# Question 6

Write a NumPy program to compute the covariance matrix of two given arrays. 

Original array1: [0 1 2] 

Original array2: [2 1 0] 

Covariance matrix of the said arrays: [[ 1. -1.] [-1. 1.]]
 

Hint: We can use the np.cov() function to calculate the covariance between these two arrays

In [44]:
# compute the covariance matrix of two given arrays.
import numpy as np

arr1 = np.array([0,1,2])
arr2 = np.array([2,1,0])

Conv_matrix = np.cov(arr1,arr2)
print(Conv_matrix)

[[ 1. -1.]
 [-1.  1.]]


# Question 7

Question: Write a program that calculates and prints the value according to the given formula: Q = Square root of [(2 * C * D)/H] 

The following are the fixed values of C and H: C is 50. H is 30. 

D is the variable whose values should be input into your program in a comma-separated sequence. (that means D contains more than value)

Example Let's assume the following comma-separated input sequence is given to the program: 100,150,180 The output of the program should be: 18,22,24 

To further explain this, we will obtain a result for each value of D:  Q1= Square root of [(2 * C * 100)/H] =18, Q2= Square root of [(2 * C * 150)/H] = 22 and Q3 = Square root of [(2 * C * 180)/H]  = 24

Hints: If the output received is in decimal form, it should be rounded off to its nearest value (for example, if the output received is 26.0, it should be printed as 26) In case of input data being supplied to the question, it should be assumed to be a console input.

In [80]:
# formula: Q = Square root of [(2 * C * D)/H] with C is 50. H is 30
# D is the variable in a comma-separated sequence. 
#The Input D =100,150,180 ,The output of the program should be: 18,22,24  (100,150,180) --> (18,22,24)


# Input D as comma-separated --> Output as int(arr)

def inputD():
    n =input("Enter 3 Numbers comma-separated: ")
    arr = n.split(",")
    for i in range(len(arr)):
        arr[i] = int(arr[i])
    print("D: ", n, "// D as a tuple: ",tuple(arr))    
    
    return arr


# Calculate Q with D as Array as Input

def calculate(arr):
    import math
    C = 50
    H = 30
    arr2 = ['']
    for i in range(0,len(arr)):
        arr[i] = int(math.sqrt((2*C*arr[i])/H))
        if i< len(arr)-1:
            arr2[0] = arr2[0] + str(arr[i]) +","
        else:
            arr2[0] = arr2[0] + str(arr[i])
            
    return arr2[0], arr

a =calculate(inputD())

print("Q = ",a[0], "// Q as a tuple : ",tuple(a[1]))


Enter 3 Numbers comma-separated: 100,150,180
D:  100,150,180 // D as a tuple:  (100, 150, 180)
Q =  18,22,24 // Q as a tuple :  (18, 22, 24)
