In [3]:
x = 19
y = 10
x%y*3/(x-y)

3.0

In [6]:
a ="welcome to coding world"
len(a)
a[len(a)-9]


'i'

In [2]:
a = "Hello Word"
try:
    ist = int(a)
except:
    ist = -1

ist

-1

In [4]:
def double(n):
    return n*2
print(double(10))

y = lambda x : x*2
print(y(10))

20
20


In [6]:
def großer (a,b):
    if a >b:
        return a 
    else:
        return b
großer(1,2)


2

In [10]:
r = lambda a,b: a if a>b else b
r(5,3)

5

In [17]:
names =["Alan", "Gregory", "Zlatan", "Jonas", "Tom", "Augustine"]
names.sort(reverse =True)
print(names)
names.sort(key = lambda x : len(x),reverse =True)
names

['Zlatan', 'Tom', 'Jonas', 'Gregory', 'Augustine', 'Alan']


['Augustine', 'Gregory', 'Zlatan', 'Jonas', 'Alan', 'Tom']

In [10]:
counter = 0
while counter<3:
    print("Inside Loop")
    counter += 1
else:
    print("Inside else")

Inside Loop
Inside Loop
Inside Loop
Inside else


In [13]:
i = 1
while i<6:
    print(i)
    i+=1
    

1
2
3
4
5


In [15]:
def name():
    x = input("Give your Name: ")
    print("My Name is " + x )
name()

Give your Name: Abderrahmen
My Name is Abderrahmen


In [13]:
x = map(len,('apple', 'banana', 'cherry'))
print(list(x))

[5, 6, 6]


In [19]:
import math as m
m.sqrt(4)

x = map(m.sqrt, (4,5,6,7))

print(list(x))

[2.0, 2.23606797749979, 2.449489742783178, 2.6457513110645907]


In [20]:
T1 = (1,2,3,4)
T2 = (5,6,7,8)
a = list(map(lambda m,n: m+n, T1,T2))
a

[6, 8, 10, 12]

In [41]:
import numpy as np
New_array = np.array([1,2,3])
New_array1 = np.array([[1,2,3],[3,4,5]])
print(New_array)
print(New_array1)
print(New_array1.shape)
print(type(New_array1))
print(New_array1[0,0],New_array1[1,1])
print(New_array1)
print(New_array1.shape)
print(np.shape(New_array1))
print()
print(New_array1.reshape(2,3))


[1 2 3]
[[1 2 3]
 [3 4 5]]
(2, 3)
<class 'numpy.ndarray'>
1 4
[[1 2 3]
 [3 4 5]]
(2, 3)
(2, 3)

[[1 2 3]
 [3 4 5]]


In [38]:
print(np.zeros(3))
print(np.full(3,5))
print()
print(np.eye(3))
print()
print(np.ones(5))

[0. 0. 0.]
[5 5 5]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[1. 1. 1. 1. 1.]


In [54]:
Value = np.random.random()
print(Value)
Value1 = np.random.random((2,2))
print(Value1)
Value3 = np.random.randint(3,19,size=(2,2))
print(Value3)


0.7522487189455431
[[0.60203226 0.82102947]
 [0.77921727 0.43098369]]
[[14  8]
 [ 4 15]]


In [60]:
X = np.random.randint(3,19,size=(3,4))
Y = np.random.randint(8,78,size=(3,4))
print(X)
print(Y)
print("---")
A = np.add(X,Y)
A1 = X + Y
B = np.subtract(X,Y)
B1 = X - Y
print(A)
print(A1)
print(B)
print(B1)

[[ 8 18  4 18]
 [ 5 11 13 18]
 [ 7 13  4  8]]
[[47 26 20 75]
 [52 51 64 26]
 [54 75 70 46]]
---
[[55 44 24 93]
 [57 62 77 44]
 [61 88 74 54]]
[[55 44 24 93]
 [57 62 77 44]
 [61 88 74 54]]
[[-39  -8 -16 -57]
 [-47 -40 -51  -8]
 [-47 -62 -66 -38]]
[[-39  -8 -16 -57]
 [-47 -40 -51  -8]
 [-47 -62 -66 -38]]


In [68]:
S = np.array([[1,2,3],[3,8,5]])
Bool_index = S>2
print(Bool_index)
print(S[Bool_index])
print(S[S>2])

[[False False  True]
 [ True  True  True]]
[3 3 8 5]
[3 3 8 5]


In [70]:
a = np.array([[9, 18], [19, 10]])
print( a > 10)

[[False  True]
 [ True False]]


In [74]:
import numpy as np
import pandas as pd
array = np.array([1,2,3])
Serie1 = pd.Series(array)
print(Serie1)
List = [1,2,3]
Serie2 = pd.Series(List)
print(Serie2)


0    1
1    2
2    3
dtype: int32
0    1
1    2
2    3
dtype: int64


In [78]:
Color = ["C","G","D"]
Color1 = ["C","N","D"]
A1 = pd.Series([1,2,3], index =Color)
A2 = pd.Series([7,4,9], index =Color1)
print(A1+A2)

C     8.0
D    12.0
G     NaN
N     NaN
dtype: float64


In [80]:
sum(A1)

6

In [81]:
import numpy as np
import pandas as pd
my_numpy_array=np.random.randn(3,4)
df=pd.DataFrame(my_numpy_array, columns=list("abcd"))
print(df)

          a         b         c         d
0 -1.268167  1.463729 -1.284096 -1.738472
1  1.065986 -1.085599  0.111746 -1.967236
2 -0.185474  1.905271  0.974223  1.195657


In [82]:
df


a         b         c         d
0 -1.268167  1.463729 -1.284096 -1.738472
1  1.065986 -1.085599  0.111746 -1.967236
2 -0.185474  1.905271  0.974223  1.195657

In [87]:
New_Data = pd.read_csv("Exp.csv")
New_Data

Unnamed: 0       name  age      city
0           0       Jack   34     Paris
1           1     Thomas   30      Roma
2           2  Alexandre   16  New York

In [88]:
New_Data["age"].describe()

count     3.000000
mean     26.666667
std       9.451631
min      16.000000
25%      23.000000
50%      30.000000
75%      32.000000
max      34.000000
Name: age, dtype: float64

In [90]:
New_Data["name"].describe()

count        3
unique       3
top       Jack
freq         1
Name: name, dtype: object

In [91]:
New_Data.iloc[1]

Unnamed: 0         1
name          Thomas
age               30
city            Roma
Name: 1, dtype: object

In [93]:
New_Data

Unnamed: 0       name  age      city
0           0       Jack   34     Paris
1           1     Thomas   30      Roma
2           2  Alexandre   16  New York

In [94]:
New_Data[New_Data["age"] >17]

Unnamed: 0    name  age   city
0           0    Jack   34  Paris
1           1  Thomas   30   Roma

In [95]:
New_Data[New_Data["name"] =="Jack"]

Unnamed: 0  name  age   city
0           0  Jack   34  Paris

In [96]:
New_Data

Unnamed: 0       name  age      city
0           0       Jack   34     Paris
1           1     Thomas   30      Roma
2           2  Alexandre   16  New York

In [115]:
New_Data["Last name"] = pd.Series(["Müller","John","Sala"])

In [116]:
New_Data

Unnamed: 0       name  age      city       Full Name Last name
0           0       Jack   34     Paris     Jack Müller    Müller
1           1     Thomas   30      Roma     Thomas John      John
2           2  Alexandre   16  New York  Alexandre Sala      Sala

In [120]:
New_Data

Unnamed: 0       name  age      city Last name
0           0       Jack   34     Paris    Müller
1           1     Thomas   30      Roma      John
2           2  Alexandre   16  New York      Sala

In [122]:
New_Data["Full Name"] =  New_Data["name"] + " " + New_Data["Last name"]

New_Data = New_Data.drop("Full Name", axis = 1)
New_Data

Unnamed: 0       name  age      city Last name
0           0       Jack   34     Paris    Müller
1           1     Thomas   30      Roma      John
2           2  Alexandre   16  New York      Sala

In [123]:
New_Data["Full name"] =  New_Data["name"] + " " + New_Data["Last name"]


In [124]:
New_Data

Unnamed: 0       name  age      city Last name       Full name
0           0       Jack   34     Paris    Müller     Jack Müller
1           1     Thomas   30      Roma      John     Thomas John
2           2  Alexandre   16  New York      Sala  Alexandre Sala

In [126]:
New_Data = New_Data.drop(["name","Last name"], axis = 1)
New_Data

Unnamed: 0  age      city       Full name
0           0   34     Paris     Jack Müller
1           1   30      Roma     Thomas John
2           2   16  New York  Alexandre Sala

In [135]:
D = New_Data.dropna(axis =0, how = "all", inplace =False,thresh=3)
D

Unnamed: 0  age      city       Full name
0           0   34     Paris     Jack Müller
1           1   30      Roma     Thomas John
2           2   16  New York  Alexandre Sala

In [148]:
New_Data.iloc[1:2,1:2] = "NaN"

In [150]:
New_Data

Unnamed: 0  age      city       Full name
0           0   34     Paris     Jack Müller
1           1  NaN      Roma     Thomas John
2           2   16  New York  Alexandre Sala

In [157]:
D = New_Data.dropna(axis =1)
D

Unnamed: 0  age      city       Full name
0           0   34     Paris     Jack Müller
1           1  NaN      Roma     Thomas John
2           2   16  New York  Alexandre Sala

In [158]:
D

Unnamed: 0  age      city       Full name
0           0   34     Paris     Jack Müller
1           1  NaN      Roma     Thomas John
2           2   16  New York  Alexandre Sala

In [159]:
New_Data

Unnamed: 0  age      city       Full name
0           0   34     Paris     Jack Müller
1           1  NaN      Roma     Thomas John
2           2   16  New York  Alexandre Sala

In [163]:
NN = pd.concat([New_Data,D])

In [164]:
NN


Unnamed: 0  age      city       Full name
0           0   34     Paris     Jack Müller
1           1  NaN      Roma     Thomas John
2           2   16  New York  Alexandre Sala
0           0   34     Paris     Jack Müller
1           1  NaN      Roma     Thomas John
2           2   16  New York  Alexandre Sala

In [168]:
user_input = input("Enter the input ")

try:
    int(user_input)
    it_is = True
except ValueError:
    it_is = False

print(it_is)

Enter the input 8
True


In [172]:
a = input("Enter the input ")
it_is = False
while it_is == False:
    try:
        int(a)
        it_is = True
    except ValueError:
        it_is = False
        print("Do it again")
        a = input("Enter the input ")    

Enter the input ö
Do it again
Enter the input a
Do it again
Enter the input 1


In [178]:
it_is = False
while it_is == False:
    a = input("Enter the input ")
    try:
        int(a)
        it_is = True
    except ValueError:
        it_is = False
        print("The Given Number is not an integer, Please give an integer:")

Enter the input l
The Given Number is not an integer, Please give an integer:
Enter the input 1


In [208]:
Number = input("Given Nummer: ")
Number = float(Number)
int(Number)

#print(int(Number))

Given Nummer: 2.0


2

In [206]:
num1 = "5.9"
num3 = float(num1)

int(num3)


5

In [210]:
a == -0.2 >-1.0 
a

'1'

In [5]:
import os.path
filename ="Lec2.txt"
extension = os.path.splitext(filename)[1]
extension

'.txt'

In [6]:
files = os.listdir(".")
for f in files:
    os.rename(f, f+filetype(f))

NameError: name 'filetype' is not defined

In [8]:
import sys 

print(sys.argv)

['C:\\Users\\Abderrahmen Mansour\\anaconda3\\lib\\site-packages\\ipykernel_launcher.py', '-f', 'C:\\Users\\Abderrahmen Mansour\\AppData\\Roaming\\jupyter\\runtime\\kernel-72ca8898-c162-498b-a2cf-ceea826d9cbb.json']


In [9]:
import os
print("Current File Name : ",os.path.realpath(__file__))

NameError: name '__file__' is not defined

In [10]:
import os
print(os.path.basename(your_path))

NameError: name 'your_path' is not defined

In [11]:
import os
print(os.path.basename(your_path))

NameError: name 'your_path' is not defined

In [12]:
os.getcwd()

'C:\\Users\\Abderrahmen Mansour\\Documents\\Project\\Projects\\IA\\Lec'

In [13]:
os.listdir()

['.ipynb_checkpoints', 'Exp.csv', 'Lec1.ipynb', 'Lec2.ipynb']

In [20]:
import os

def absolute_file_paths(directory):
    path = os.path.abspath(directory)
    return [entry.path for entry in os.scandir(path) if entry.is_file()]

absolute_file_paths('C:\\Users\\Abderrahmen Mansour\\Documents\\Project\\Projects\\IA\\Lec')

['C:\\Users\\Abderrahmen Mansour\\Documents\\Project\\Projects\\IA\\Lec\\Exp.csv',
 'C:\\Users\\Abderrahmen Mansour\\Documents\\Project\\Projects\\IA\\Lec\\Lec1.ipynb',
 'C:\\Users\\Abderrahmen Mansour\\Documents\\Project\\Projects\\IA\\Lec\\Lec2.ipynb']

In [21]:
import sys
print(sys.argv[0])

C:\Users\Abderrahmen Mansour\anaconda3\lib\site-packages\ipykernel_launcher.py


In [23]:
import __main__ as main
print(main.__file__)

AttributeError: module '__main__' has no attribute '__file__'

In [25]:
import sys    
import os    
file_name =  os.path.basename(sys.argv[0])
file_name

'ipykernel_launcher.py'

In [26]:
import inspect
print (inspect.getfile(inspect.currentframe()))

C:\Users\ABDERR~1\AppData\Local\Temp/ipykernel_16336/4145296073.py


In [27]:
from pathlib import Path
Path(__file__).stem

NameError: name '__file__' is not defined

In [28]:
import os
os.path.split(sys.argv[0])[1]

'ipykernel_launcher.py'

In [32]:
import os 
 
print(os.path.basename(__file__))

NameError: name '__file__' is not defined

In [30]:
print(os.getcwd())
print(sys.argv[0])
print(os.path.dirname(os.path.realpath('__file__')))

C:\Users\Abderrahmen Mansour\Documents\Project\Projects\IA\Lec
C:\Users\Abderrahmen Mansour\anaconda3\lib\site-packages\ipykernel_launcher.py
C:\Users\Abderrahmen Mansour\Documents\Project\Projects\IA\Lec


In [33]:
def find_data_file(filename):
    if getattr(sys, 'frozen', False):
        # The application is frozen
        datadir = os.path.dirname(sys.executable)
    else:
        # The application is not frozen
        # Change this bit to match where you store your data files:
        datadir = os.path.dirname(__file__)

    return os.path.join(datadir, filename)

In [35]:
import inspect
src_file_path = inspect.getfile(lambda: None)
src_file_path

'C:\\Users\\ABDERR~1\\AppData\\Local\\Temp/ipykernel_16336/633098899.py'

In [37]:
os.path.dirname(os.path.abspath(<span class="hljs-string">"__file__"</span>))

SyntaxError: invalid syntax (Temp/ipykernel_16336/4215947995.py, line 1)

In [38]:
os.path.abspath('')

'C:\\Users\\Abderrahmen Mansour\\Documents\\Project\\Projects\\IA\\Lec'

In [40]:
import os
os.listdir()

['.ipynb_checkpoints', 'Exp.csv', 'Lec1.ipynb', 'Lec2.ipynb']

In [54]:
for top, dirs, files in os.walk(os.getcwd()):
    print("Printing directories...")
    for dir in dirs:
        print(os.path.join(top, dir))
    print("Printing files....")
    for file in files:
        print(os.path.join(top, file))


Printing directories...
C:\Users\Abderrahmen Mansour\Documents\Project\Projects\IA\Lec\.ipynb_checkpoints
Printing files....
C:\Users\Abderrahmen Mansour\Documents\Project\Projects\IA\Lec\Exp.csv
C:\Users\Abderrahmen Mansour\Documents\Project\Projects\IA\Lec\Lec1.ipynb
C:\Users\Abderrahmen Mansour\Documents\Project\Projects\IA\Lec\Lec2.ipynb
C:\Users\Abderrahmen Mansour\Documents\Project\Projects\IA\Lec\Lec3.ipynb
Printing directories...
Printing files....
C:\Users\Abderrahmen Mansour\Documents\Project\Projects\IA\Lec\.ipynb_checkpoints\Lec2-checkpoint.ipynb
C:\Users\Abderrahmen Mansour\Documents\Project\Projects\IA\Lec\.ipynb_checkpoints\Lec3-checkpoint.ipynb


In [42]:
os.getcwd()

'C:\\Users\\Abderrahmen Mansour\\Documents\\Project\\Projects\\IA\\Lec'

In [47]:
print(os.walk(os.getcwd()))


<generator object _walk at 0x000001932F292E40>


In [58]:
os.path.join(top, dir)

'C:\\Users\\Abderrahmen Mansour\\Documents\\Project\\Projects\\IA\\Lec\\.ipynb_checkpoints\\.ipynb_checkpoints'

In [56]:
file

'Lec3-checkpoint.ipynb'

In [60]:
for dir in dirs:
    print(os.path.join(top, dir))

In [61]:
filedir

NameError: name 'filedir' is not defined

In [62]:
import pathlib
print(pathlib.Path('/path/file.ext').suffix)

.ext


In [73]:
MyDict = {}  
for i in range (1,8,1):
    MyDict[i] = i*i

print(MyDict) 
print(MyDict.keys(),MyDict.values())

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49}
dict_keys([1, 2, 3, 4, 5, 6, 7]) dict_values([1, 4, 9, 16, 25, 36, 49])


In [74]:
x = 0
if x < 2 :
    print('Small')
elif x < 10 :
    print('Medium')
else :
    print('LARGE')
print('All done')

Small
All done


In [78]:
x = -2
if x < 2 :
    print('Below 2')
elif x >= 2 :
     print('Two or more')
else :
    print('Something else')

Below 2


In [79]:
astr = 'Hello Bob'
istr = 0
try:
    istr = int(astr)
except:
    istr = -1

In [80]:
istr

-1

In [81]:
if x == 6 :
    print('Is 6')
    print('Is Still 6')
    print('Third 6')

In [4]:
username = input("Choose a username: ")
final_username = username.replace(3, "")
final_username

Choose a username: abcdef


TypeError: replace() argument 1 must be str, not int

In [7]:
str = input("Give a non/empty String: ")

# checking if string with space is empty
print("Check if the string is empty : ", end="")
if(str and not str.isspace()):
    print("The string is not empty")
else:
    print("The string is empty")

Give a non/empty String: Hello
Check if the string is empty : The string is not empty


In [21]:
print(str)
str = "a"
while str  and  not str.isspace():
    str = input("Give a non/empty String: ")

# checking if string with space is empty
    print("Check if the string is empty : ", end="")
    if(str and not str.isspace()):
        print("The string is not empty")
    else:
        print("The string is empty")
    

a


In [41]:
# test, if Space here?

str = "a"
if str.isspace():
    print(str.isspace())
    print("The string is empty")
else:
    print(str.isspace())
    print("The string is not empty")
    
print(str.isspace() and  str)

False
The string is not empty
False


In [60]:
str = "a"
print(str)
if not str.isspace():
    print(str.isspace())
    print("The string is empty")
else:
    print(str.isspace())
    print("The string is not empty")
    
print(str.isspace() and  str)

a
False
The string is empty
False


In [66]:
# Check if empty
strA = ""

# checking if string is empty
print("Check if the strA is empty : ", end="")
if(not strA):
    print("The string is empty")
else:
    print("No it is not empty")

Check if the strA is empty : The string is empty


In [69]:
# Check if empty

strA = "a"

# checking if string with space is empty
print("Check if the string is empty : ", end="")
if(len(strA)):
    print("The string is not empty")
else:
    print("The string is empty")

Check if the string is empty : The string is not empty


In [79]:
# retry if empty
strA = ""
while  not len(strA):
    
    strA = input("Give a non/empty String: ")

Give a non/empty String: 
Give a non/empty String: Hello


In [81]:
my_variable = "56"

if isinstance(my_variable, int):
     

print(isinstance(my_variable, int))

False


In [89]:
# Check if Input Int

user_input = input("Enter the input: ")

try:
    int(user_input)
    it_is = True
except ValueError:
    it_is = False

print(it_is)

Enter the input: Hell
False


In [91]:
# Check if Input Int, else try again!!
it_is = False 
while it_is == False:
    Number = input("Given Nummer: ")
    try:
        int(Number)
        it_is = True
 
    except ValueError : 
        it_is = False

Given Nummer: ka
Given Nummer: 1


In [97]:
Str = input("Give a non/empty String: ")


# Check if Input Int, else try again!!


it_is = False 
while it_is == False:
    Number = input("Given Nummer: ")
    try:
        int(Number)
        it_is = True
    except ValueError : 
        it_is = False

# n = 0 len-1


if int(Number) > len(Str):
    print("invalid Number")
else:
    Str =Str[:int(Number)] + Str[int(Number)+1:len(Str)]
    print(Str)
            
 

Give a non/empty String: Hello
Given Nummer: 3
Helo


In [101]:
def Checkifempty():
    Str = ""
    while  not len(Str):
        Str = input("Give a non/empty String: ")
    return Str
Checkifempty()

Give a non/empty String: 
Give a non/empty String: 
Give a non/empty String: Hello


'Hello'

In [102]:
    while it_is == False:
        n = input("Give a Valid index n: ")
        try:
            int(n)
            it_is = True
        except ValueError : 
            it_is = False

In [103]:
if n >= len(Str) or n < 0 :
    print("invalid Number")
else:
    Str =Str[:n] + Str[n+1:len(Str)]
    print(Str)

NameError: name 'n' is not defined

In [ ]:
 Str = input("Give a non/empty String: ")
    
while n >= len(Str) or n < 0:
    print("invalid Number")
    