In [3]:
x = 19
y = 10
x%y*3/(x-y)

3.0

In [6]:
a ="welcome to coding world"
len(a)
a[len(a)-9]


'i'

In [2]:
a = "Hello Word"
try:
    ist = int(a)
except:
    ist = -1

ist

-1

In [4]:
def double(n):
    return n*2
print(double(10))

y = lambda x : x*2
print(y(10))

20
20


In [6]:
def großer (a,b):
    if a >b:
        return a 
    else:
        return b
großer(1,2)


2

In [10]:
r = lambda a,b: a if a>b else b
r(5,3)

5

In [17]:
names =["Alan", "Gregory", "Zlatan", "Jonas", "Tom", "Augustine"]
names.sort(reverse =True)
print(names)
names.sort(key = lambda x : len(x),reverse =True)
names

['Zlatan', 'Tom', 'Jonas', 'Gregory', 'Augustine', 'Alan']


['Augustine', 'Gregory', 'Zlatan', 'Jonas', 'Alan', 'Tom']

In [10]:
counter = 0
while counter<3:
    print("Inside Loop")
    counter += 1
else:
    print("Inside else")

Inside Loop
Inside Loop
Inside Loop
Inside else


In [13]:
i = 1
while i<6:
    print(i)
    i+=1
    

1
2
3
4
5


In [15]:
def name():
    x = input("Give your Name: ")
    print("My Name is " + x )
name()

Give your Name: Abderrahmen
My Name is Abderrahmen


In [13]:
x = map(len,('apple', 'banana', 'cherry'))
print(list(x))

[5, 6, 6]


In [19]:
import math as m
m.sqrt(4)

x = map(m.sqrt, (4,5,6,7))

print(list(x))

[2.0, 2.23606797749979, 2.449489742783178, 2.6457513110645907]


In [20]:
T1 = (1,2,3,4)
T2 = (5,6,7,8)
a = list(map(lambda m,n: m+n, T1,T2))
a

[6, 8, 10, 12]

In [41]:
import numpy as np
New_array = np.array([1,2,3])
New_array1 = np.array([[1,2,3],[3,4,5]])
print(New_array)
print(New_array1)
print(New_array1.shape)
print(type(New_array1))
print(New_array1[0,0],New_array1[1,1])
print(New_array1)
print(New_array1.shape)
print(np.shape(New_array1))
print()
print(New_array1.reshape(2,3))


[1 2 3]
[[1 2 3]
 [3 4 5]]
(2, 3)
<class 'numpy.ndarray'>
1 4
[[1 2 3]
 [3 4 5]]
(2, 3)
(2, 3)

[[1 2 3]
 [3 4 5]]


In [38]:
print(np.zeros(3))
print(np.full(3,5))
print()
print(np.eye(3))
print()
print(np.ones(5))

[0. 0. 0.]
[5 5 5]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[1. 1. 1. 1. 1.]


In [54]:
Value = np.random.random()
print(Value)
Value1 = np.random.random((2,2))
print(Value1)
Value3 = np.random.randint(3,19,size=(2,2))
print(Value3)


0.7522487189455431
[[0.60203226 0.82102947]
 [0.77921727 0.43098369]]
[[14  8]
 [ 4 15]]


In [60]:
X = np.random.randint(3,19,size=(3,4))
Y = np.random.randint(8,78,size=(3,4))
print(X)
print(Y)
print("---")
A = np.add(X,Y)
A1 = X + Y
B = np.subtract(X,Y)
B1 = X - Y
print(A)
print(A1)
print(B)
print(B1)

[[ 8 18  4 18]
 [ 5 11 13 18]
 [ 7 13  4  8]]
[[47 26 20 75]
 [52 51 64 26]
 [54 75 70 46]]
---
[[55 44 24 93]
 [57 62 77 44]
 [61 88 74 54]]
[[55 44 24 93]
 [57 62 77 44]
 [61 88 74 54]]
[[-39  -8 -16 -57]
 [-47 -40 -51  -8]
 [-47 -62 -66 -38]]
[[-39  -8 -16 -57]
 [-47 -40 -51  -8]
 [-47 -62 -66 -38]]


In [68]:
S = np.array([[1,2,3],[3,8,5]])
Bool_index = S>2
print(Bool_index)
print(S[Bool_index])
print(S[S>2])

[[False False  True]
 [ True  True  True]]
[3 3 8 5]
[3 3 8 5]


In [70]:
a = np.array([[9, 18], [19, 10]])
print( a > 10)

[[False  True]
 [ True False]]


In [74]:
import numpy as np
import pandas as pd
array = np.array([1,2,3])
Serie1 = pd.Series(array)
print(Serie1)
List = [1,2,3]
Serie2 = pd.Series(List)
print(Serie2)


0    1
1    2
2    3
dtype: int32
0    1
1    2
2    3
dtype: int64


In [78]:
Color = ["C","G","D"]
Color1 = ["C","N","D"]
A1 = pd.Series([1,2,3], index =Color)
A2 = pd.Series([7,4,9], index =Color1)
print(A1+A2)

C     8.0
D    12.0
G     NaN
N     NaN
dtype: float64


In [80]:
sum(A1)

6

In [81]:
import numpy as np
import pandas as pd
my_numpy_array=np.random.randn(3,4)
df=pd.DataFrame(my_numpy_array, columns=list("abcd"))
print(df)

          a         b         c         d
0 -1.268167  1.463729 -1.284096 -1.738472
1  1.065986 -1.085599  0.111746 -1.967236
2 -0.185474  1.905271  0.974223  1.195657


In [82]:
df


a         b         c         d
0 -1.268167  1.463729 -1.284096 -1.738472
1  1.065986 -1.085599  0.111746 -1.967236
2 -0.185474  1.905271  0.974223  1.195657

In [87]:
New_Data = pd.read_csv("Exp.csv")
New_Data

Unnamed: 0       name  age      city
0           0       Jack   34     Paris
1           1     Thomas   30      Roma
2           2  Alexandre   16  New York

In [88]:
New_Data["age"].describe()

count     3.000000
mean     26.666667
std       9.451631
min      16.000000
25%      23.000000
50%      30.000000
75%      32.000000
max      34.000000
Name: age, dtype: float64

In [90]:
New_Data["name"].describe()

count        3
unique       3
top       Jack
freq         1
Name: name, dtype: object

In [91]:
New_Data.iloc[1]

Unnamed: 0         1
name          Thomas
age               30
city            Roma
Name: 1, dtype: object

In [93]:
New_Data

Unnamed: 0       name  age      city
0           0       Jack   34     Paris
1           1     Thomas   30      Roma
2           2  Alexandre   16  New York

In [94]:
New_Data[New_Data["age"] >17]

Unnamed: 0    name  age   city
0           0    Jack   34  Paris
1           1  Thomas   30   Roma

In [95]:
New_Data[New_Data["name"] =="Jack"]

Unnamed: 0  name  age   city
0           0  Jack   34  Paris

In [96]:
New_Data

Unnamed: 0       name  age      city
0           0       Jack   34     Paris
1           1     Thomas   30      Roma
2           2  Alexandre   16  New York

In [115]:
New_Data["Last name"] = pd.Series(["Müller","John","Sala"])

In [116]:
New_Data

Unnamed: 0       name  age      city       Full Name Last name
0           0       Jack   34     Paris     Jack Müller    Müller
1           1     Thomas   30      Roma     Thomas John      John
2           2  Alexandre   16  New York  Alexandre Sala      Sala

In [120]:
New_Data

Unnamed: 0       name  age      city Last name
0           0       Jack   34     Paris    Müller
1           1     Thomas   30      Roma      John
2           2  Alexandre   16  New York      Sala

In [122]:
New_Data["Full Name"] =  New_Data["name"] + " " + New_Data["Last name"]

New_Data = New_Data.drop("Full Name", axis = 1)
New_Data

Unnamed: 0       name  age      city Last name
0           0       Jack   34     Paris    Müller
1           1     Thomas   30      Roma      John
2           2  Alexandre   16  New York      Sala

In [123]:
New_Data["Full name"] =  New_Data["name"] + " " + New_Data["Last name"]


In [124]:
New_Data

Unnamed: 0       name  age      city Last name       Full name
0           0       Jack   34     Paris    Müller     Jack Müller
1           1     Thomas   30      Roma      John     Thomas John
2           2  Alexandre   16  New York      Sala  Alexandre Sala

In [126]:
New_Data = New_Data.drop(["name","Last name"], axis = 1)
New_Data

Unnamed: 0  age      city       Full name
0           0   34     Paris     Jack Müller
1           1   30      Roma     Thomas John
2           2   16  New York  Alexandre Sala

In [135]:
D = New_Data.dropna(axis =0, how = "all", inplace =False,thresh=3)
D

Unnamed: 0  age      city       Full name
0           0   34     Paris     Jack Müller
1           1   30      Roma     Thomas John
2           2   16  New York  Alexandre Sala

In [148]:
New_Data.iloc[1:2,1:2] = "NaN"

In [150]:
New_Data

Unnamed: 0  age      city       Full name
0           0   34     Paris     Jack Müller
1           1  NaN      Roma     Thomas John
2           2   16  New York  Alexandre Sala

In [157]:
D = New_Data.dropna(axis =1)
D

Unnamed: 0  age      city       Full name
0           0   34     Paris     Jack Müller
1           1  NaN      Roma     Thomas John
2           2   16  New York  Alexandre Sala

In [158]:
D

Unnamed: 0  age      city       Full name
0           0   34     Paris     Jack Müller
1           1  NaN      Roma     Thomas John
2           2   16  New York  Alexandre Sala

In [159]:
New_Data

Unnamed: 0  age      city       Full name
0           0   34     Paris     Jack Müller
1           1  NaN      Roma     Thomas John
2           2   16  New York  Alexandre Sala

In [163]:
NN = pd.concat([New_Data,D])

In [164]:
NN


Unnamed: 0  age      city       Full name
0           0   34     Paris     Jack Müller
1           1  NaN      Roma     Thomas John
2           2   16  New York  Alexandre Sala
0           0   34     Paris     Jack Müller
1           1  NaN      Roma     Thomas John
2           2   16  New York  Alexandre Sala

In [168]:
user_input = input("Enter the input ")

try:
    int(user_input)
    it_is = True
except ValueError:
    it_is = False

print(it_is)

Enter the input 8
True


In [172]:
a = input("Enter the input ")
it_is = False
while it_is == False:
    try:
        int(a)
        it_is = True
    except ValueError:
        it_is = False
        print("Do it again")
        a = input("Enter the input ")    

Enter the input ö
Do it again
Enter the input a
Do it again
Enter the input 1


In [178]:
it_is = False
while it_is == False:
    a = input("Enter the input ")
    try:
        int(a)
        it_is = True
    except ValueError:
        it_is = False
        print("The Given Number is not an integer, Please give an integer:")

Enter the input l
The Given Number is not an integer, Please give an integer:
Enter the input 1


In [208]:
Number = input("Given Nummer: ")
Number = float(Number)
int(Number)

#print(int(Number))

Given Nummer: 2.0


2

In [206]:
num1 = "5.9"
num3 = float(num1)

int(num3)


5

In [210]:
a == -0.2 >-1.0 
a

'1'