In [3]:
# Preprocessing phase.
import pandas as pd
data = pd.read_csv("newfood.csv")
# Head of the Dataset
data.head(2)

id                                             title  pricePerServing  \
0   1                         Fried Anchovies with Sage           5.6051   
1   2  Anchovies Appetizer With Breadcrumbs & Scallions           0.8206   

   weightPerServing  vegetarian  vegan  glutenFree  dairyFree  sustainable  \
0               226       False  False       False       True        False   
1                33       False  False       False       True        False   

   veryHealthy  ...  Vitamin B5/mg Vitamin B6/mg  Vitamin E/mg  Fiber/g  \
0        False  ...           1.38          0.26          1.09     1.16   
1        False  ...           0.20          0.04          0.29     0.38   

   Vitamin A/IU  Vitamin D/µg Vitamin K/µg Vitamin C/mg  Alcohol/g  Caffeine/g  
0         154.8          0.29         0.00          0.0        0.0         0.0  
1           0.0          0.00         7.18          0.0        0.0         0.0  

[2 rows x 59 columns]

In [4]:
data.isnull().sum()

id                         0
title                      0
pricePerServing            0
weightPerServing           0
vegetarian                 0
vegan                      0
glutenFree                 0
dairyFree                  0
sustainable                0
veryHealthy                0
veryPopular                0
gaps                       0
lowFodmap                  0
ketogenic                  0
whole30                    0
readyInMinutes             0
spoonacularSourceUrl       0
image                      5
aggregateLikes             0
spoonacularScore           0
healthScore                0
percentProtein             0
percentFat                 0
percentCarbs               0
dishTypes                 78
ingredients                0
cuisines                1378
calories                   0
Fat/g                      0
Saturated Fat/g            0
Carbohydrates/g            0
Sugar/g                    0
Cholesterol/mg             0
Sodium/mg                  0
Protein/g     

In [33]:
# Preprocessing phase.
import pandas as pd
data = pd.read_csv("IndianFoodDatasetCSV.csv")
# Head of the Dataset
data.head(2)

Srno                                         RecipeName  \
0     1                               Masala Karela Recipe   
1     2  टमाटर पुलियोगरे रेसिपी - Spicy Tomato Rice (Re...   

         TranslatedRecipeName  \
0        Masala Karela Recipe   
1  Spicy Tomato Rice (Recipe)   

                                         Ingredients  \
0  6 Karela (Bitter Gourd/ Pavakkai) - deseeded,S...   
1  2-1/2 कप चावल - पका ले,3 टमाटर,3 छोटा चमच्च बी...   

                               TranslatedIngredients  PrepTimeInMins  \
0  6 Karela (Bitter Gourd/ Pavakkai) - deseeded,S...              15   
1  2-1 / 2 cups rice - cooked, 3 tomatoes, 3 teas...               5   

   CookTimeInMins  TotalTimeInMins  Servings               Cuisine  \
0              30               45         6                Indian   
1              10               15         3  South Indian Recipes   

        Course               Diet  \
0    Side Dish  Diabetic Friendly   
1  Main Course         Vegetarian   

                                        Instructions  \
0  To begin making the Masala Karela Recipe,de-se...   
1  टमाटर पुलियोगरे बनाने के लिए सबसे पहले टमाटर क...   

                              TranslatedInstructions  \
0  To begin making the Masala Karela Recipe,de-se...   
1  To make tomato puliogere, first cut the tomato...   

                                                 URL  
0  https://www.archanaskitchen.com/masala-karela-...  
1  http://www.archanaskitchen.com/spicy-tomato-ri...

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6871 entries, 0 to 6870
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   Srno                    6871 non-null   int64 
 1   RecipeName              6871 non-null   object
 2   TranslatedRecipeName    6871 non-null   object
 3   Ingredients             6865 non-null   object
 4   TranslatedIngredients   6865 non-null   object
 5   PrepTimeInMins          6871 non-null   int64 
 6   CookTimeInMins          6871 non-null   int64 
 7   TotalTimeInMins         6871 non-null   int64 
 8   Servings                6871 non-null   int64 
 9   Cuisine                 6871 non-null   object
 10  Course                  6871 non-null   object
 11  Diet                    6871 non-null   object
 12  Instructions            6871 non-null   object
 13  TranslatedInstructions  6871 non-null   object
 14  URL                     6871 non-null   object
dtypes: i

In [5]:
data.isnull().sum()

Srno                      0
RecipeName                0
TranslatedRecipeName      0
Ingredients               6
TranslatedIngredients     6
PrepTimeInMins            0
CookTimeInMins            0
TotalTimeInMins           0
Servings                  0
Cuisine                   0
Course                    0
Diet                      0
Instructions              0
TranslatedInstructions    0
URL                       0
dtype: int64

In [11]:
data = pd.read_csv("recipes.csv")
# Head of the Dataset
data.head(2)

RecipeId                               Name  AuthorId AuthorName CookTime  \
0        38  Low-Fat Berry Blue Frozen Dessert      1533     Dancer    PT24H   
1        39                            Biryani      1567   elly9812    PT25M   

  PrepTime TotalTime         DatePublished  \
0    PT45M  PT24H45M  1999-08-09T21:46:00Z   
1     PT4H   PT4H25M  1999-08-29T13:12:00Z   

                                         Description  \
0  Make and share this Low-Fat Berry Blue Frozen ...   
1  Make and share this Biryani recipe from Food.com.   

                                              Images  ... SaturatedFatContent  \
0  c("https://img.sndimg.com/food/image/upload/w_...  ...                 1.3   
1  c("https://img.sndimg.com/food/image/upload/w_...  ...                16.6   

  CholesterolContent SodiumContent CarbohydrateContent  FiberContent  \
0                8.0          29.8                37.1           3.6   
1              372.8         368.4                84.4           9.0   

   SugarContent  ProteinContent  RecipeServings  RecipeYield  \
0          30.2             3.2             4.0          NaN   
1          20.4            63.4             6.0          NaN   

                                  RecipeInstructions  
0  c("Toss 2 cups berries with sugar.", "Let stan...  
1  c("Soak saffron in warm milk for 5 minutes and...  

[2 rows x 28 columns]

In [12]:
data.isnull().sum()

RecipeId                           0
Name                               0
AuthorId                           0
AuthorName                         0
CookTime                       82545
PrepTime                           0
TotalTime                          0
DatePublished                      0
Description                        5
Images                             1
RecipeCategory                   751
Keywords                       17237
RecipeIngredientQuantities         3
RecipeIngredientParts              0
AggregatedRating              253223
ReviewCount                   247489
Calories                           0
FatContent                         0
SaturatedFatContent                0
CholesterolContent                 0
SodiumContent                      0
CarbohydrateContent                0
FiberContent                       0
SugarContent                       0
ProteinContent                     0
RecipeServings                182911
RecipeYield                   348071
R

In [13]:
data = pd.read_csv("reviews.csv")
# Head of the Dataset
data.head(2)

ReviewId  RecipeId  AuthorId     AuthorName  Rating  \
0         2       992      2008      gayg msft       5   
1         7      4384      1634  Bill Hilbrich       4   

                                              Review         DateSubmitted  \
0       better than any you can get at a restaurant!  2000-01-25T21:44:00Z   
1  I cut back on the mayo, and made up the differ...  2001-10-17T16:49:59Z   

           DateModified  
0  2000-01-25T21:44:00Z  
1  2001-10-17T16:49:59Z

In [14]:
data = pd.read_csv("Food Ingredients and Recipe Dataset with Image Name Mapping.csv")
# Head of the Dataset
data.head(2)


Unnamed: 0                                              Title  \
0           0  Miso-Butter Roast Chicken With Acorn Squash Pa...   
1           1                    Crispy Salt and Pepper Potatoes   

                                         Ingredients  \
0  ['1 (3½–4-lb.) whole chicken', '2¾ tsp. kosher...   
1  ['2 large egg whites', '1 pound new potatoes (...   

                                        Instructions  \
0  Pat chicken dry with paper towels, season all ...   
1  Preheat oven to 400°F and line a rimmed baking...   

                                          Image_Name  \
0  miso-butter-roast-chicken-acorn-squash-panzanella   
1         crispy-salt-and-pepper-potatoes-dan-kluger   

                                 Cleaned_Ingredients  
0  ['1 (3½–4-lb.) whole chicken', '2¾ tsp. kosher...  
1  ['2 large egg whites', '1 pound new potatoes (...

In [15]:
data.isnull().sum()

Unnamed: 0             0
Title                  5
Ingredients            0
Instructions           8
Image_Name             0
Cleaned_Ingredients    0
dtype: int64

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13501 entries, 0 to 13500
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Unnamed: 0           13501 non-null  int64 
 1   Title                13496 non-null  object
 2   Ingredients          13501 non-null  object
 3   Instructions         13493 non-null  object
 4   Image_Name           13501 non-null  object
 5   Cleaned_Ingredients  13501 non-null  object
dtypes: int64(1), object(5)
memory usage: 633.0+ KB


In [17]:
data = pd.read_csv("recipes_w_search_terms.csv")
# Head of the Dataset
data.head(2)

id                                   name  \
0   96313            Grilled Garlic Cheese Grits   
1  232037  Simple Shrimp and Andouille Jambalaya   

                                         description  \
0  We love grits, this is another good way to ser...   
1  Simple, easy and very tasty for when you are i...   

                                         ingredients  \
0  ['water', 'grits', 'salt', 'cheddar cheese', '...   
1  ['onion', 'red bell pepper', 'garlic cloves', ...   

                                 ingredients_raw_str serving_size  servings  \
0  ["4   cups    water","1   cup   uncooked old f...    1 (155 g)         8   
1  ["1   medium    onion, chopped coarse ","1   m...    1 (366 g)         4   

                                               steps  \
0  ['I a sauce pan, bring water to a boil; slowly...   
1  ['In a food processor, pulse the onion, red pe...   

                                                tags  \
0  ['time-to-make', 'course', 'main-ingredient', ...   
1  ['60-minutes-or-less', 'time-to-make', 'course...   

                                        search_terms  
0  {'diabetic', 'low-calorie', 'vegetarian', 'low...  
1                               {'dinner', 'shrimp'}

In [18]:
data.isnull().sum()

id                        0
name                      0
description            9598
ingredients               0
ingredients_raw_str       0
serving_size              0
servings                  0
steps                     0
tags                      0
search_terms              0
dtype: int64

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 494963 entries, 0 to 494962
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype 
---  ------               --------------   ----- 
 0   id                   494963 non-null  int64 
 1   name                 494963 non-null  object
 2   description          485365 non-null  object
 3   ingredients          494963 non-null  object
 4   ingredients_raw_str  494963 non-null  object
 5   serving_size         494963 non-null  object
 6   servings             494963 non-null  int64 
 7   steps                494963 non-null  object
 8   tags                 494963 non-null  object
 9   search_terms         494963 non-null  object
dtypes: int64(2), object(8)
memory usage: 37.8+ MB


In [21]:
data = pd.read_csv("epi_r.csv")
# Head of the Dataset
data.head(2)

title  rating  calories  protein  \
0              Lentil, Apple, and Turkey Wrap    2.500     426.0     30.0   
1  Boudin Blanc Terrine with Red Onion Confit    4.375     403.0     18.0   

    fat  sodium  #cakeweek  #wasteless  22-minute meals  3-ingredient recipes  \
0   7.0   559.0        0.0         0.0              0.0                   0.0   
1  23.0  1439.0        0.0         0.0              0.0                   0.0   

   ...  yellow squash  yogurt  yonkers  yuca  zucchini  cookbooks  leftovers  \
0  ...            0.0     0.0      0.0   0.0       0.0        0.0        0.0   
1  ...            0.0     0.0      0.0   0.0       0.0        0.0        0.0   

   snack  snack week  turkey  
0    0.0         0.0     1.0  
1    0.0         0.0     0.0  

[2 rows x 680 columns]

In [22]:
data.isnull().sum()

title            0
rating           0
calories      4117
protein       4162
fat           4183
              ... 
cookbooks        0
leftovers        0
snack            0
snack week       0
turkey           0
Length: 680, dtype: int64

In [23]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20052 entries, 0 to 20051
Columns: 680 entries, title to turkey
dtypes: float64(679), object(1)
memory usage: 104.0+ MB


In [24]:
data = pd.read_csv("RecipeNLG_dataset.csv")
# Head of the Dataset
data.head(2)

Unnamed: 0                  title  \
0           0    No-Bake Nut Cookies   
1           1  Jewell Ball'S Chicken   

                                         ingredients  \
0  ["1 c. firmly packed brown sugar", "1/2 c. eva...   
1  ["1 small jar chipped beef, cut up", "4 boned ...   

                                          directions  \
0  ["In a heavy 2-quart saucepan, mix brown sugar...   
1  ["Place chipped beef on bottom of baking dish....   

                                              link    source  \
0   www.cookbooks.com/Recipe-Details.aspx?id=44874  Gathered   
1  www.cookbooks.com/Recipe-Details.aspx?id=699419  Gathered   

                                                 NER  
0  ["brown sugar", "milk", "vanilla", "nuts", "bu...  
1  ["beef", "chicken breasts", "cream of mushroom...

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2231142 entries, 0 to 2231141
Data columns (total 7 columns):
 #   Column       Dtype 
---  ------       ----- 
 0   Unnamed: 0   int64 
 1   title        object
 2   ingredients  object
 3   directions   object
 4   link         object
 5   source       object
 6   NER          object
dtypes: int64(1), object(6)
memory usage: 119.2+ MB


In [26]:
data.isnull().sum()

Unnamed: 0     0
title          0
ingredients    0
directions     0
link           0
source         0
NER            0
dtype: int64

In [29]:
data = pd.read_csv("recipes.csv")
# Head of the Dataset
data.head(2)


UnicodeDecodeError: 'utf-8' codec can't decode byte 0xae in position 229728: invalid start byte

In [30]:
data = pd.read_csv("food_recipes.csv")
# Head of the Dataset
data.head(2)

recipe_title  \
0  Roasted Peppers And Mushroom Tortilla Pizza Re...   
1  Thakkali Gotsu Recipe | Thakkali Curry | Spicy...   

                                                 url record_health  \
0  https://www.archanaskitchen.com/roasted-pepper...          good   
1  https://www.archanaskitchen.com/tomato-gotsu-r...          good   

   vote_count    rating                                        description  \
0         434  4.958525   is a quicker version pizza to satisfy your cr...   
1        3423  4.932223   also known as the   is a quick and easy to ma...   

                cuisine  course        diet prep_time cook_time  \
0               Mexican  Dinner  Vegetarian      15 M      15 M   
1  South Indian Recipes   Lunch  Vegetarian      10 M      20 M   

                                         ingredients  \
0  Tortillas|Extra Virgin Olive Oil|Garlic|Mozzar...   
1  Sesame (Gingelly) Oil|Mustard seeds (Rai/ Kadu...   

                                        instructions             author  \
0  To begin making the Roasted Peppers And Mushro...  Divya Shivaraman    
1  To begin making Tomato Gotsu Recipe/ Thakkali ...      Archana Doshi   

                                                tags              category  
0  Party Food Recipes|Tea Party Recipes|Mushroom ...         Pizza Recipes  
1  Vegetarian Recipes|Tomato Recipes|South Indian...  Indian Curry Recipes

In [31]:
data.isnull().sum()

recipe_title       0
url                0
record_health      0
vote_count         0
rating             0
description       15
cuisine           66
course           155
diet             151
prep_time         30
cook_time         30
ingredients       12
instructions       0
author             0
tags              79
category           0
dtype: int64

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8009 entries, 0 to 8008
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   recipe_title   8009 non-null   object 
 1   url            8009 non-null   object 
 2   record_health  8009 non-null   object 
 3   vote_count     8009 non-null   int64  
 4   rating         8009 non-null   float64
 5   description    7994 non-null   object 
 6   cuisine        7943 non-null   object 
 7   course         7854 non-null   object 
 8   diet           7858 non-null   object 
 9   prep_time      7979 non-null   object 
 10  cook_time      7979 non-null   object 
 11  ingredients    7997 non-null   object 
 12  instructions   8009 non-null   object 
 13  author         8009 non-null   object 
 14  tags           7930 non-null   object 
 15  category       8009 non-null   object 
dtypes: float64(1), int64(1), object(14)
memory usage: 1001.2+ KB


In [35]:
from statistics import covariance

x = [55.36, 57.75, 55.26, 55.96, 56.66]
y = [55.75, 55.49, 55.12, 54.70, 53.94]
covariance(x, y)
# 0.75

ImportError: cannot import name 'covariance' from 'statistics' (C:\Users\Abderrahmen Mansour\anaconda3\lib\statistics.py)

In [41]:
import statistics
import numpy as np
x = [55.36, 57.75, 55.26, 55.96, 56.66]
y = [55.75, 55.49, 55.12, 54.70, 53.94]

array1 = np.array(x)
array2 = np.array(y)
covariance = np.cov(array1, array2)
covariance1 = np.cov(array1, array2)[0][1]
print(covariance,covariance1)

[[ 1.06522  -0.099725]
 [-0.099725  0.50765 ]] -0.09972499999999838


In [42]:
np.array(x).mean()

56.198

In [45]:
np.array(y).mean()

55.0

In [46]:
arr1 = array1 -np.array(x).mean()
arr1

array([-0.838,  1.552, -0.938, -0.238,  0.462])

In [47]:
arr2 = array2 -np.array(y).mean()
arr2

array([ 0.75,  0.49,  0.12, -0.3 , -1.06])

In [48]:
arr1 * arr2

array([-0.6285 ,  0.76048, -0.11256,  0.0714 , -0.48972])

In [49]:
Sum = -0.6285 +  0.76048 + -0.11256 +  0.0714 + -0.48972

In [50]:
Sum

-0.39889999999999987

In [51]:
Sum/4

-0.09972499999999997

In [55]:
a = [80,  65,   86,  84,  78,  76,  79]
b = [70, 70 ,85, 86, 60, 75, 86] 
array1 = np.array(a)
array2 = np.array(b)

In [59]:
array2.mean()

76.0

In [58]:
70+ 70 +85+ 86+ 60+ 75+86

532

In [67]:
(array1 - 78.3)**2

array([2.8900e+00, 1.7689e+02, 5.9290e+01, 3.2490e+01, 9.0000e-02,
       5.2900e+00, 4.9000e-01])

In [76]:
(array1 - 78.3)*(array2 - 76.0)

array([-10.2,  79.8,  69.3,  57. ,   4.8,   2.3,   7. ])

In [77]:
array1 - 78.3

array([  1.7, -13.3,   7.7,   5.7,  -0.3,  -2.3,   0.7])

In [84]:
sum(array1 - 78.3)

-0.0999999999999801

In [96]:
m = 1.7+ -13.3+   7.7+   5.7+  -0.3 +  -2.3+   0.7
m

-0.10000000000000098

In [80]:
(array1 - 78.3)

array([  1.7, -13.3,   7.7,   5.7,  -0.3,  -2.3,   0.7])

In [87]:
(array2 - 76.0)

array([ -6.,  -6.,   9.,  10., -16.,  -1.,  10.])

In [97]:
-6.+  -6.+   9.+  10.+ -16.+  -1.+  10.

0.0

In [89]:
(array1 - 78.3)**2

array([2.8900e+00, 1.7689e+02, 5.9290e+01, 3.2490e+01, 9.0000e-02,
       5.2900e+00, 4.9000e-01])

In [95]:
2.8900e+00 + 1.7689e+02+ 5.9290e+01+ 3.2490e+01+ 9.0000e-02+5.2900e+00+ 4.9000e-01

277.42999999999995

In [93]:
(array2 - 76.0)**2

array([ 36.,  36.,  81., 100., 256.,   1., 100.])

In [94]:
36.+  36.+  81.+ 100.+ 256.+   1.+ 100

610.0

In [98]:
(array1 - 78.3)*(array2 - 76.0)

array([-10.2,  79.8,  69.3,  57. ,   4.8,   2.3,   7. ])

In [99]:
sum((array1 - 78.3)*(array2 - 76.0))

209.99999999999997

In [100]:
-10.2+  79.8+  69.3+  57. +   4.8+  2.3+   7. 

210.0

In [102]:
b1 = 210/277.43
b1

0.7569476985185452

In [103]:
b0 = 76.0 - (0.76) *(78.3)

In [104]:
b0

16.492000000000004

In [106]:
16.5+ 0.76* 75

73.5

In [107]:
277.43/7

39.63285714285714

In [108]:
import math
math.sqrt(277.43/7)

6.295463219085403

In [110]:
6.3**2

39.69

In [111]:
610/7

87.14285714285714

In [112]:
math.sqrt (610/7) 

9.335033858688309

In [120]:
( (1/7 ) * 210) / ( 6.29 * 9.34) **2

0.008692129966744904

In [134]:
( (1/7 ) * 210 / ( 6.29 * 9.34) )**2

0.26076389900234714

In [124]:
0.1*0.1

0.010000000000000002

In [126]:
(array1 - 78.3)**2

array([2.8900e+00, 1.7689e+02, 5.9290e+01, 3.2490e+01, 9.0000e-02,
       5.2900e+00, 4.9000e-01])

In [128]:
array1 - 78.3

array([  1.7, -13.3,   7.7,   5.7,  -0.3,  -2.3,   0.7])

In [131]:
sum ((array2 - 76)**2)

610

In [132]:
sum((array2 - 76)*((array1 - 78.3)))

209.99999999999997

In [133]:
210/277.43

0.7569476985185452