# Question 1

Write a Python program to convert an array to an ordinary list with the same items.

we can use the np.tolist() function



In [1]:
import numpy as np
array= np.array([[1,2,3],[4,5,6],[7,8,9]])
list1 = array.tolist()
print(list1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


# Question 2 

Write a NumPy program to compute the sum of the diagonal elements of a given array.

Hint: Two methods to solve this problem: 1. manually(without direct function). 2. using the trace function



In [2]:
import numpy as np
array= np.array([[1,2,3],[4,5,6],[7,8,9]])
sum = np.trace(array)
print("The Sum of the diagonal elements is:",sum)

The Sum of the diagonal elements is: 15


# Question 3

Given an array of your choice, get all the values higher than X :

if a = [[1,2],[3,5]] and x = 2 :  then 3 and 5 are higher than 2. 



In [4]:
import numpy as np
array= np.array([[1,2,3],[4,5,6],[7,8,9]])
x = int(input("Give a Value x:"))
# True/False Array
# print(array>x) 
#print The Result as np.Array
print(array[array>x])
#print The Result in one Line
print(*array[array>x], sep=', ')  

Give a Value x:2
[3 4 5 6 7 8 9]
3, 4, 5, 6, 7, 8, 9


# Question 4

Given two arrays, A & B have the same shape. 

The task is to apply addition by hand: C is the new array. 



In [6]:
import numpy as np
n = int(input("Give the number of rows: ")) 
p = int(input("Give the number of columns: "))
A = np.random.randint(2, 10, size=(n,p))
B = np.random.randint(9, 17, size=(n,p))
C = A + B 
print(C)

Give the number of rows: 5
Give the number of columns: 2
[[21 16]
 [14 16]
 [21 13]
 [20 13]
 [12 18]]


# Question 5

Write a NumPy program to subtract the mean of each row of a given matrix.

Hint: use the mean function

 

In [7]:
import numpy as np
array= np.array([[1,2,3],[4,5,6],[7,8,9]])
#Average Rows
average_row = np.mean(array,axis = 1)
print(average_row.reshape(3,1))

print(average_row.T)
print((array.T -average_row).T)
a, b = array.shape
for i in range (a):
    for j in range (b):
        R = array[i,j]- average_row[i]
print(R)    
print("average_row: ",average_row)
#adapt the row Colomb to subtract mean row
ad = (average_row*np.ones((3, 3))).T
print("\nadapted Array :\n" ,ad)
# Array subtract from Average Rows
Result = array - ad
print("Result: \n", Result)

[[2.]
 [5.]
 [8.]]
[2. 5. 8.]
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
1.0
average_row:  [2. 5. 8.]

adapted Array :
 [[2. 2. 2.]
 [5. 5. 5.]
 [8. 8. 8.]]
Result: 
 [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
