In [1]:
import numpy as np

In [2]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [4]:
np.linspace(1., 4., 7)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [6]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [7]:
np.diag(a)

array([1, 4])

In [8]:
np.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [22]:
np.vander(np.linspace(0, 10, 5), 2)

array([[ 0. ,  1. ],
       [ 2.5,  1. ],
       [ 5. ,  1. ],
       [ 7.5,  1. ],
       [10. ,  1. ]])

In [23]:
np.vander((1, 2, 3, 4), 4)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [25]:
np.vander([1, 2, 3, 4], 4)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [1]:
f = open("python.txt")
f.read()

f.readline()

'What is Python language?                                                \n'

In [32]:
f.read(4)    # read the next 4 data


' is '

In [33]:
f.read()     # read in the rest till end of file


'Python language?                                                \nPython is a widely used high-level, general-purpose, interpreted, dynamic programming language.Its design philosophy emphasizes code readability, and its syntax allows programmers to express concepts in fewer lines of code than possible in \nlanguages such as C++ or Java. \nPython supports multiple programming paradigms, including object-oriented, imperative and functional programming or procedural styles. It features a dynamic type system and automatic memory management and has a large and comprehensive standard library.The best way we learn anything is by practice and exercise questions. We  have started this section for those (beginner to intermediate) who are familiar with Python.'

In [34]:
f.read()  # further reading returns empty sting

''