In [6]:
class Car(object):
    def __init__(self, model, passengers, color, speed):
        self.model = model
        self.passengers = passengers
        self.color = color
        self.speed = speed

    def accelerate(self):
        self.speed = self.speed + 2
        print (self.speed)

bmw = Car("BMW", 4, "red", 5)
ferrari = Car("Ferrari", 2, "black", 10)
ford = Car("Ford", 6, "blue", 6)

bmw.accelerate()
print (bmw.color)

ferrari.accelerate()
print (ferrari.color)
ferrari.accelerate() #note that the speed has been updated from the previous accelerate call

print (ford.passengers)
ford.accelerate()

7
red
12
black
14
6
8


In [12]:
class bar(object):
    foo = 5
bar.foo = 8  + bar.foo

In [13]:
print(bar.foo)

13


In [33]:
class IceCream(object):
    def __init__(self, flavor, numScoops, costPerScoop, remaining_icecream):
        self.flavor = flavor
        self.numScoops = numScoops
        self.costPerScoop = costPerScoop
        self.remaining_icecream = remaining_icecream

    def scoop(self):
                #shows the amount of ice cream remaining after an order is scooped
        #scoops icecream and decreases the number of scoops left
        self.remaining_icecream -= self.numScoops
        return self.remaining_icecream

    def total_cost(self):
        #vanilla ice cream is sold at a discount of half off!
        if self.flavor == "vanilla":
            total_cost = self.numScoops * .5*self.costPerScoop

        else:
            total_cost = self.numScoops * self.costPerScoop

        return total_cost
chocolate = IceCream("chocolate",4,1,6)
print (chocolate.remaining_icecream - chocolate.numScoops)
print (chocolate.scoop())
vanilla = IceCream("vanilla", 4, 2, 10)
print (vanilla.total_cost())

2
2
4.0


-2

In [37]:
class Employee:
    def __init__(self, first,last,pay):
        self.first = first
        self.last = last
        self.pay = pay
        self.email = self.first + '.' + self.last + '@company.com'

    def fullname(self):
        return self.first + ' ' + self.last
emp_1 = Employee('John','Doe',50000)
emp_2 = Employee('Jane','Doe',60000)
print(emp_1.email)
print(emp_2.first)
print(emp_1.fullname())
print(Employee.fullname(emp_2))


John.Doe@company.com
Jane
John Doe
Jane Doe


In [51]:
# parent class
class Bird:
    
    def __init__(self):
        print("Bird is ready")

    def whoisThis(self):
        print("Bird")
    def swim(self):
        print("Swim faster")

# child class
class Penguin(Bird):

    def __init__(self):
        super().__init__()
        print("Penguin is ready")

    def whoisThis(self):
        print("Penguin")

    def run(self):
        print("Run faster")

peggy = Penguin()
print('#')
peggy.whoisThis()
print('#')
peggy.swim()
print('#')
peggy.run()
a = Bird()
b = Bird()
a == b

Bird is ready
Penguin is ready
#
Penguin
#
Swim faster
#
Run faster
Bird is ready
Bird is ready


False

# 1
Write a python class named Point3D defined by x, y, and z. Define a method that returns (x, y ,z). This tells Python to represent this object in the following format: (x, y, z). Then create a variable named my_point containing a new instance of Point3D with x=1, y=2, and z=3 and print it.

In [57]:
class Point3D:
    def __init__(self,x,y,z):
        self.x = x
        self.y = y
        self.z = z
    def rueckgabe(self):
        return (self.x,self.y,self.z)

my_point=Point3D(1,2,3)
print(my_point.rueckgabe())

(1, 2, 3)


# 2
Write a Python class named Rectangle constructed by a length and width. Define two methods area and perimeter which will compute the area and the perimeter of the rectangle. Then create a variable named my_rectangle containing a new instance of Rectangle with width=3 and length = 4 and compute both of area and perimeter ( the area is expected to be 34=12 and perimeter 2(3+4)=14)

In [65]:
class Rectangle:
    def __init__(self,width,length):
        self.length = length
        self.width  = width
    def area (self):
        return self.length * self.width
    def perimeter (self):
        return (self.length + self.width) * 2

my_rectangle = Rectangle(3,4)
print("The area of the Rectangle with a width = {} and a length = {} is {} m2.".format(my_rectangle.width,my_rectangle.length,my_rectangle.area()))
print("The perimeter of the Rectangle a the width = {} and a length = {} is {} m.".format(my_rectangle.width,my_rectangle.length,my_rectangle.perimeter()))

The area of the Rectangle with a width = 3 and a length = 4 is 12 m2.
The perimeter of the Rectangle a the width = 3 and a length = 4 is 14 m.


# 3
Write a Python class named Circle constructed by its center O and radius r. Define two methods area and perimeter which will compute the area and the perimeter of the circle, and isInside() method of the class which allows to test whether a point A(x, y) belongs to the circle C(O, r) or not.

In [83]:
from math import pi
from math import sqrt
class Circle:
    def __init__(self,O,r):
        self.O = O
        self.r = r
    def area (self):
        return pi * self.r ** 2
    def perimeter (self):
        return pi * 2 * self.r
    def isInside(self,x,y):
        d = sqrt((x-self.O) ** 2 +(y-self.r) ** 2)
        print(d)
        if self.r >= d:
            return print("inside")
        else:
            return print("Outside")

cir1 = Circle(1,4)
cir2 = Circle(3,4)
print(cir1.area())
print(cir1.perimeter())
print(cir1.isInside(1,1))
print(cir2.isInside(1,9))

50.26548245743669
25.132741228718345
3.0
inside
None
5.385164807134504
Outside
None


# 4
Suppose we want to model a bank account with support for deposit and withdraw operations. Let’s create a python class named bank defined by its balance. Define two methods deposit and withdraw to compute the new amount of each operation.



In [89]:
class bank:
    def __init__(self,amount):
        self.amount = amount
    def deposit(self,deposit):
        self.amount = self.amount - deposit 
        return self.amount 
    def withdraw(self,withdraw):
        self.amount = self.amount + withdraw
        return self.amount 

bank1 = bank(5000)
print(bank1.deposit(500))
print(bank1.withdraw(100))

4500
4600


In [90]:
from math import pi as p
print(p)

3.141592653589793


In [102]:
my_dictionary =	{"knowledge": "Data Science","tool": "python","year": 2020}
print(my_dictionary.keys())
print(my_dictionary.values())
print(my_dictionary.items())

dict_keys(['knowledge', 'tool', 'year'])
dict_values(['Data Science', 'python', 2020])
dict_items([('knowledge', 'Data Science'), ('tool', 'python'), ('year', 2020)])


In [108]:
for key in my_dictionary.keys():     # Loop Through dictionary keys
     print(key)

for value in my_dictionary.values():    #  Loop Through dictionary values
     print(value)

for item in my_dictionary.items():     # Loop Through dictionary items
      print(item)
print(len(my_dictionary))

knowledge
tool
year
Data Science
python
2020
('knowledge', 'Data Science')
('tool', 'python')
('year', 2020)
3


In [113]:
my_dictionary =	{"knowledge": "Data Science","tool": "python","year": 2020}
my_dictionary["learn"] = True  #add True value with "learn" key
print(my_dictionary)
my_dictionary.pop("tool")     #remove "tool" item
print(my_dictionary) 

del my_dictionary["learn"]
print(my_dictionary)

{'knowledge': 'Data Science', 'tool': 'python', 'year': 2020, 'learn': True}
{'knowledge': 'Data Science', 'year': 2020, 'learn': True}
{'knowledge': 'Data Science', 'year': 2020}


In [114]:
tuple1 = ("a", "b" , "c")
tuple2 = (1, 2, 3)
tuple3 = tuple1 + tuple2     #join the two tuples by + operator
print(tuple3) 

('a', 'b', 'c', 1, 2, 3)


In [116]:
List1 = ["a", "b" , "c"]
List2 = [1, 2, 3]
List3 = List1 + List2     #join the two tuples by + operator
print(List3) 

['a', 'b', 'c', 1, 2, 3]


In [6]:
import numpy as np 

In [12]:
arr1=np.array([1,2,3])
arr2=np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr2)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [13]:
a = np.array([(1, 2), (3, 4), (5,6)])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
a.shape

(3, 2)

In [15]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
a[-1]

array([5, 6])

In [17]:
a[-1,-1]

6

In [23]:
print(a[1,:])
print(a[1])
print(a[:,1])
print(a[:,-1])

[3 4]
[3 4]
[2 4 6]
[2 4 6]


In [24]:
A = np.array([[0,1,2],[3,4,5]])

In [25]:
A

array([[0, 1, 2],
       [3, 4, 5]])

In [30]:
print(A[:, [0,2]])
print(A[:, 0:2])

[[0 2]
 [3 5]]
[[0 1]
 [3 4]]


In [31]:
import numpy as np
value=np.random.random()
print(value)

0.7226470894105703


In [32]:
array=np.random.random((2,2))
print(array)

[[0.67775424 0.1386601 ]
 [0.78274194 0.48413467]]


In [33]:
array=np.random.randint(2, 10, size=(2,4))
print(array)

[[4 9 4 6]
 [2 8 6 2]]


In [34]:
array=np.zeros(3)
print(array)

[0. 0. 0.]


In [35]:
array=np.full(3, 5)
print(array)

[5 5 5]


In [36]:
array=np.eye(2)
print(array)

[[1. 0.]
 [0. 1.]]


In [37]:
array=np.ones(5)
print(array)

[1. 1. 1. 1. 1.]


In [40]:
import numpy as np 
a=np.array([1, 2, 5])
b=np.array([5,7, 13])
print(a+b)

[ 6  9 18]


In [41]:
import numpy as np
x=np.array([[1,2],[3,4]], dtype=np.float64)
y=np.array([[5,6],[7,8]], dtype=np.float64)

In [43]:
A=np.add(x, y)
A

array([[ 6.,  8.],
       [10., 12.]])

In [44]:
A=x+y
A

array([[ 6.,  8.],
       [10., 12.]])

In [45]:
Z=np.subtract(x, y)
Z

array([[-4., -4.],
       [-4., -4.]])

In [46]:
Z=x-y
Z

array([[-4., -4.],
       [-4., -4.]])

In [47]:
import socket
hostname = socket.gethostname()
IpAdresse = socket.gethostbyname(hostname)
print(IpAdresse)

192.168.105.77


In [4]:
a = int( input ("Gib mal a: "))
b = int (input ("Gib mal b: "))
x = lambda a,b:a*b
print(x(a,b))

Gib mal a: 5
Gib mal b: 3
15


In [8]:
tuple1 = (1,2,3)
tuple2 = (6,5,4)
x = lambda a,b:a+b
m = list(map(x,tuple1,tuple2))
print(m)

[7, 7, 7]


In [14]:
str ={"male":2,"female" :5,"male":5,"male":60,"female":6}

n = list(map(lambda str: str["male"] = 1, str))

TypeError: <lambda>() missing 1 required positional argument: 'b'

In [24]:
Value = input("Typed less than 6 Characters: ")
LetterNum = 0
for Letter in Value:
    LetterNum += 1
    print("Letter", LetterNum,"is", Letter)
    #LetterNum += 1
    print(LetterNum)
    if LetterNum > 6:
        print("Your String is too Long")
        break

Typed less than 6 Characters: mansou
Letter 1 is m
1
Letter 2 is a
2
Letter 3 is n
3
Letter 4 is s
4
Letter 5 is o
5
Letter 6 is u
6


In [27]:
L = [1,2,3]
L.remove(3)
L

[1, 2]

In [30]:
[1,2,3] * 3


[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [2]:
a ="Stuff;thh;hs;"
y =a.split(";")
y

['Stuff', 'thh', 'hs', '']

In [4]:
t = [5,7, 13].tuple()

AttributeError: 'list' object has no attribute 'tuple'

In [1]:
import numpy as np

In [13]:
array1 =np.eye(3)
array2 = np.ones(5)
array3 = np.zeros(3)
array4 = np.full(5,3)
array4

array([3, 3, 3, 3, 3])

In [21]:
import numpy as np
array= np.array([[1,2,3],[4,5,6],[7,8,9]])
x = int(input("Give a Value X:"))
print (array[array>5])

Give a Value X:5
[6 7 8 9]


In [24]:
import numpy as np
array= np.array([[1,2,3],[4,5,6],[7,8,9]])
x = int(input("Give a Value x:"))
print(array>x)
print(array[array>x])
a = array[array>x]
list1 = (array[array>x]).tolist()
for i in a:
    print(i)
print(*a, sep=', ')               

Give a Value x:3
[[False False False]
 [ True  True  True]
 [ True  True  True]]
[4 5 6 7 8 9]
4
5
6
7
8
9
4, 5, 6, 7, 8, 9


In [29]:
x = np.zeros(1)
x

array([0.])

In [38]:
import numpy as np
    
  
# 2D array 
arr = [[14, 17, 12, 33, 44],  
       [15, 6, 27, 8, 19], 
       [23, 2, 54, 1, 4, ]] 
    
# mean of the flattened array 
print("\nmean of arr, axis = None : ", np.mean(arr)) 
    
# mean along the axis = 0 
print("\nmean of arr, axis = 0 : ", np.mean(arr, axis = 0)) 
   
# mean along the axis = 1 
print("\nmean of arr, axis = 1 : ", np.mean(arr, axis = 1))
  
out_arr = np.arange(3)
a = np.array([3,4,5])
print("\nout_arr : ", out_arr) 
print("mean of arr, axis = 1 : ", 
      np.mean(arr, axis = 1, out = out_arr))
print("\nout_arr : ", a) 
print("mean of arr, axis = 1 : ", 
      np.mean(arr, axis = 1, out = a))
print("\nout_arr : ", a) 


mean of arr, axis = None :  18.6

mean of arr, axis = 0 :  [17.33333333  8.33333333 31.         14.         22.33333333]

mean of arr, axis = 1 :  [24.  15.  16.8]

out_arr :  [0 1 2]
mean of arr, axis = 1 :  [24 15 16]

out_arr :  [3 4 5]
mean of arr, axis = 1 :  [24 15 16]

out_arr :  [24 15 16]


In [46]:
import numpy as np

a = np.array([[4,3],[2,7]])
print(a)
print(a.T) # First Method
print(a.transpose()) # Second Method

[[4 3]
 [2 7]]
[[4 2]
 [3 7]]
[[4 2]
 [3 7]]


In [64]:
#a = np.array([[2,5,8]]).T* np.array([[1,1,1],[1,1,1],[1,1,1]])
a = np.array([[2,5,8]]).T*np.ones((3, 3))
print(a)
np.array([[1,2,3],[4,5,6],[7,8,9]])-a

[[2. 2. 2.]
 [5. 5. 5.]
 [8. 8. 8.]]


array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

In [62]:
np.array([[2,5,8]])

array([[2, 5, 8]])

In [63]:
np.array([[2,5,8]]).T

array([[2],
       [5],
       [8]])