In [11]:
import numpy as np
array= np.array([[1,2,3],[4,5,6],[7,8,9]])
#Average Rows
average_row = (np.mean(array,axis = 1))
#adapt the row Colomb to subtract mean row
print(average_row)
p = (average_row* np.ones((3, 3))).T
print(p)
np.transpose(average_row)


[2. 5. 8.]
[[2. 2. 2.]
 [5. 5. 5.]
 [8. 8. 8.]]


array([2., 5., 8.])

In [12]:

arr = np.array([np.full(3,int(average_row[0])).tolist(),np.full(3,int(average_row[1])).tolist(),np.full(3,int(average_row[2])).tolist()])
# average_row * 
print(arr)
print(array-arr)

[[2 2 2]
 [5 5 5]
 [8 8 8]]
[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]


In [5]:
import numpy as np
np.zeros((3,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
import pandas as pd
import numpy as np
array = np.array(["blue", "yellow", "pink", "purple"]) # get the array
series1 = pd.Series(array)  #create the series from the array
print(series1)
list = [19, 175, 41, 22]
series2 = pd.Series(list) #create the series from the list
print(series2)
print(series2[1])


0      blue
1    yellow
2      pink
3    purple
dtype: object
0     19
1    175
2     41
3     22
dtype: int64
175


In [13]:
import pandas as pd
color=["pink", "white", "black", "blue"]
occurence = [20, 15, 6, 43]
S=pd.Series(occurence, index=color)
print(S)
print(S["white"])

pink     20
white    15
black     6
blue     43
dtype: int64
15


In [17]:
import pandas as pd
color=["pink", "white", "black", "blue"]
S1=pd.Series([20, 15, 6, 43], index=color)
S2=pd.Series([3, 22, 9, 10], index=color)
print(S1+S2)

pink     23
white    37
black    15
blue     53
dtype: int64


In [19]:
import pandas as pd
fruits = ["apples", "oranges", "cherries", "pears"]
fruits_ro = ["mere", "oranges", "cirese", "pere"]
S = pd.Series([20, 33, 52, 10], index=fruits)
S2 = pd.Series([17, 13, 311, 32], index=fruits_ro)
print(S+S2)

apples       NaN
cherries     NaN
cirese       NaN
mere         NaN
oranges     46.0
pears        NaN
pere         NaN
dtype: float64


In [22]:
import pandas as pd
list = [['Jack', 34, 'Paris'], ['Thomas', 30, 'Roma'], 
       ['Alexandre', 16, 'New York']] 
df = pd.DataFrame(list, columns =['name', 'age', 'city'])
df

name  age      city
0       Jack   34     Paris
1     Thomas   30      Roma
2  Alexandre   16  New York

In [23]:
dictionary  = { 'name' : ['Jack', 'Thomas', 'Alexandre'],
    'age' : [34, 30, 16],
    'city' : ['Paris', 'Roma', 'New York']}

df = pd.DataFrame(dictionary)
print(df)

        name  age      city
0       Jack   34     Paris
1     Thomas   30      Roma
2  Alexandre   16  New York


In [46]:
import numpy as np
import pandas as pd
my_numpy_array=np.random.randn(3,4)
df=pd.DataFrame(my_numpy_array, columns= ["a","b","c","d"])
print(df)

          a         b         c         d
0  1.732896  0.092405  0.084133  0.551005
1 -1.900626 -2.265073  0.851167  0.992200
2  0.003810 -1.355027  1.101851 -0.011283


In [48]:
import pandas as pd
df=pd.read_csv("Dataframe.csv")
df

Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2020                     Level 1                99999   
1      2020                     Level 1                99999   
2      2020                     Level 1                99999   
3      2020                     Level 1                99999   
4      2020                     Level 1                99999   
...     ...                         ...                  ...   
37075  2013                     Level 3                 ZZ11   
37076  2013                     Level 3                 ZZ11   
37077  2013                     Level 3                 ZZ11   
37078  2013                     Level 3                 ZZ11   
37079  2013                     Level 3                 ZZ11   

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01   
1                  All industries  Dollars (millions)           H04   
2                  All industries  Dollars (millions)           H05   
3                  All industries  Dollars (millions)           H07   
4                  All industries  Dollars (millions)           H08   
...                           ...                 ...           ...   
37075  Food product manufacturing          Percentage           H37   
37076  Food product manufacturing          Percentage           H38   
37077  Food product manufacturing          Percentage           H39   
37078  Food product manufacturing          Percentage           H40   
37079  Food product manufacturing          Percentage           H41   

                                         Variable_name      Variable_category  \
0                                         Total income  Financial performance   
1      Sales, government funding, grants and subsidies  Financial performance   
2                    Interest, dividends and donations  Financial performance   
3                                 Non-operating income  Financial performance   
4                                    Total expenditure  Financial performance   
...                                                ...                    ...   
37075                                      Quick ratio       Financial ratios   
37076              Margin on sales of goods for resale       Financial ratios   
37077                                 Return on equity       Financial ratios   
37078                           Return on total assets       Financial ratios   
37079                            Liabilities structure       Financial ratios   

         Value                             Industry_code_ANZSIC06  
0      733,258  ANZSIC06 divisions A-S (excluding classes K633...  
1      660,630  ANZSIC06 divisions A-S (excluding classes K633...  
2       54,342  ANZSIC06 divisions A-S (excluding classes K633...  
3       18,285  ANZSIC06 divisions A-S (excluding classes K633...  
4      654,872  ANZSIC06 divisions A-S (excluding classes K633...  
...        ...                                                ...  
37075       52  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
37076       40  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
37077       12  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
37078        5  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
37079       46  ANZSIC06 groups C111, C112, C113, C114, C115, ...  

[37080 rows x 10 columns]

In [63]:
dictionary  = { 'name' : ['Jack', 'Thomas', 'Alexandre'],
    'age' : [34, 30, 16],
    'city' : ['Paris', 'Roma', 'New York']}

df = pd.DataFrame(dictionary)
#print(df)
df.to_csv("Data.csv")

list = [['Jack', 34, 'Paris'], ['Thomas', 30, 'Roma'], 
       ['Alexandre', 16, 'New York']] 
n = pd.DataFrame(list, columns =['name', 'age', 'city'])
n.to_csv("Data1.csv")
new_data = pd.read_csv("Data1.csv")
new_data
# new_data.head(5)

Unnamed: 0       name  age      city
0           0       Jack   34     Paris
1           1     Thomas   30      Roma
2           2  Alexandre   16  New York

In [1]:
import pandas as pd
color=["pink", "white", "black", "blue"]
S1=pd.Series([20, 15, 6, 43], index=color)
S2=pd.Series([3, 22, 9, 10], index=color)
print(S1+S2)

pink     23
white    37
black    15
blue     53
dtype: int64


In [9]:
import pandas as pd
color=["pink", "white", "black", "blue"]
color1=["pink", "white", "black", " s"]
S1=pd.Series([20, 15, 6, 43], index=color)
S2=pd.Series([3, 22, 9, 10], index=color1)
print(S1+S2)

 s        NaN
black    15.0
blue      NaN
pink     23.0
white    37.0
dtype: float64


In [11]:
import pandas as pd
list = [['Jack', 34, 'Paris'], ['Thomas', 30, 'Roma'], 
       ['Alexandre', 16, 'New York']] 
df = pd.DataFrame(list, columns =['name', 'age', 'city'])

In [12]:
df

name  age      city
0       Jack   34     Paris
1     Thomas   30      Roma
2  Alexandre   16  New York

In [13]:
dictionary  = { 'name' : ['Jack', 'Thomas', 'Alexandre'],
    'age' : [34, 30, 16],
    'city' : ['Paris', 'Roma', 'New York']}

df = pd.DataFrame(dictionary)
print(df)

        name  age      city
0       Jack   34     Paris
1     Thomas   30      Roma
2  Alexandre   16  New York


In [22]:
import numpy as np
import pandas as pd
my_numpy_array=np.random.randn(3,4)
df=pd.DataFrame(my_numpy_array, columns=["a","b","c","d"])
print(df)

          a         b         c         d
0 -1.380347  0.013119 -1.232623  1.032401
1  0.204221  0.012116  0.867135  0.566151
2 -0.426542 -0.192079 -0.081663 -1.091227


In [25]:
df=pd.read_csv("Dataframe.csv")
df

Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2020                     Level 1                99999   
1      2020                     Level 1                99999   
2      2020                     Level 1                99999   
3      2020                     Level 1                99999   
4      2020                     Level 1                99999   
...     ...                         ...                  ...   
37075  2013                     Level 3                 ZZ11   
37076  2013                     Level 3                 ZZ11   
37077  2013                     Level 3                 ZZ11   
37078  2013                     Level 3                 ZZ11   
37079  2013                     Level 3                 ZZ11   

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01   
1                  All industries  Dollars (millions)           H04   
2                  All industries  Dollars (millions)           H05   
3                  All industries  Dollars (millions)           H07   
4                  All industries  Dollars (millions)           H08   
...                           ...                 ...           ...   
37075  Food product manufacturing          Percentage           H37   
37076  Food product manufacturing          Percentage           H38   
37077  Food product manufacturing          Percentage           H39   
37078  Food product manufacturing          Percentage           H40   
37079  Food product manufacturing          Percentage           H41   

                                         Variable_name      Variable_category  \
0                                         Total income  Financial performance   
1      Sales, government funding, grants and subsidies  Financial performance   
2                    Interest, dividends and donations  Financial performance   
3                                 Non-operating income  Financial performance   
4                                    Total expenditure  Financial performance   
...                                                ...                    ...   
37075                                      Quick ratio       Financial ratios   
37076              Margin on sales of goods for resale       Financial ratios   
37077                                 Return on equity       Financial ratios   
37078                           Return on total assets       Financial ratios   
37079                            Liabilities structure       Financial ratios   

         Value                             Industry_code_ANZSIC06  
0      733,258  ANZSIC06 divisions A-S (excluding classes K633...  
1      660,630  ANZSIC06 divisions A-S (excluding classes K633...  
2       54,342  ANZSIC06 divisions A-S (excluding classes K633...  
3       18,285  ANZSIC06 divisions A-S (excluding classes K633...  
4      654,872  ANZSIC06 divisions A-S (excluding classes K633...  
...        ...                                                ...  
37075       52  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
37076       40  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
37077       12  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
37078        5  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
37079       46  ANZSIC06 groups C111, C112, C113, C114, C115, ...  

[37080 rows x 10 columns]

In [26]:
dictionary  = { 'name' : ['Jack', 'Thomas', 'Alexandre'],
    'age' : [34, 30, 16],
    'city' : ['Paris', 'Roma', 'New York']}

df = pd.DataFrame(dictionary)
print(df)

        name  age      city
0       Jack   34     Paris
1     Thomas   30      Roma
2  Alexandre   16  New York


In [30]:
df.to_csv("exp.csv")
Data_new = pd.read_csv("exp.csv")
Data_new.head(2)

Unnamed: 0    name  age   city
0           0    Jack   34  Paris
1           1  Thomas   30   Roma

In [35]:
Data_new1 = pd.read_csv("Dataframe.csv")
print("##############info#######")
print(Data_new1.info())
print("##############head#######")
print(Data_new1.head())
print("#########tail##########")
print(Data_new1.tail())
print("########decribe############")
print(Data_new1.describe())


##############info#######
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37080 entries, 0 to 37079
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   Year                         37080 non-null  int64 
 1   Industry_aggregation_NZSIOC  37080 non-null  object
 2   Industry_code_NZSIOC         37080 non-null  object
 3   Industry_name_NZSIOC         37080 non-null  object
 4   Units                        37080 non-null  object
 5   Variable_code                37080 non-null  object
 6   Variable_name                37080 non-null  object
 7   Variable_category            37080 non-null  object
 8   Value                        37080 non-null  object
 9   Industry_code_ANZSIC06       37080 non-null  object
dtypes: int64(1), object(9)
memory usage: 2.8+ MB
None
##############head#######
   Year Industry_aggregation_NZSIOC Industry_code_NZSIOC Industry_name_NZSIOC  \
0  2020            

In [36]:
Data_new1[1:3]

Year Industry_aggregation_NZSIOC Industry_code_NZSIOC Industry_name_NZSIOC  \
1  2020                     Level 1                99999       All industries   
2  2020                     Level 1                99999       All industries   

                Units Variable_code  \
1  Dollars (millions)           H04   
2  Dollars (millions)           H05   

                                     Variable_name      Variable_category  \
1  Sales, government funding, grants and subsidies  Financial performance   
2                Interest, dividends and donations  Financial performance   

     Value                             Industry_code_ANZSIC06  
1  660,630  ANZSIC06 divisions A-S (excluding classes K633...  
2   54,342  ANZSIC06 divisions A-S (excluding classes K633...

In [43]:
Data_new1[["Year","Industry_aggregation_NZSIOC"]]

Year Industry_aggregation_NZSIOC
0      2020                     Level 1
1      2020                     Level 1
2      2020                     Level 1
3      2020                     Level 1
4      2020                     Level 1
...     ...                         ...
37075  2013                     Level 3
37076  2013                     Level 3
37077  2013                     Level 3
37078  2013                     Level 3
37079  2013                     Level 3

[37080 rows x 2 columns]

In [147]:
Data_new2 =Data_new1.set_index("Year")
Data_new2

Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
Year                                                    
2020                     Level 1                99999   
2020                     Level 1                99999   
2020                     Level 1                99999   
2020                     Level 1                99999   
2020                     Level 1                99999   
...                          ...                  ...   
2013                     Level 3                 ZZ11   
2013                     Level 3                 ZZ11   
2013                     Level 3                 ZZ11   
2013                     Level 3                 ZZ11   
2013                     Level 3                 ZZ11   

            Industry_name_NZSIOC               Units Variable_code  \
Year                                                                 
2020              All industries  Dollars (millions)           H01   
2020              All industries  Dollars (millions)           H04   
2020              All industries  Dollars (millions)           H05   
2020              All industries  Dollars (millions)           H07   
2020              All industries  Dollars (millions)           H08   
...                          ...                 ...           ...   
2013  Food product manufacturing          Percentage           H37   
2013  Food product manufacturing          Percentage           H38   
2013  Food product manufacturing          Percentage           H39   
2013  Food product manufacturing          Percentage           H40   
2013  Food product manufacturing          Percentage           H41   

                                        Variable_name      Variable_category  \
Year                                                                           
2020                                     Total income  Financial performance   
2020  Sales, government funding, grants and subsidies  Financial performance   
2020                Interest, dividends and donations  Financial performance   
2020                             Non-operating income  Financial performance   
2020                                Total expenditure  Financial performance   
...                                               ...                    ...   
2013                                      Quick ratio       Financial ratios   
2013              Margin on sales of goods for resale       Financial ratios   
2013                                 Return on equity       Financial ratios   
2013                           Return on total assets       Financial ratios   
2013                            Liabilities structure       Financial ratios   

        Value                             Industry_code_ANZSIC06  
Year                                                              
2020  733,258  ANZSIC06 divisions A-S (excluding classes K633...  
2020  660,630  ANZSIC06 divisions A-S (excluding classes K633...  
2020   54,342  ANZSIC06 divisions A-S (excluding classes K633...  
2020   18,285  ANZSIC06 divisions A-S (excluding classes K633...  
2020  654,872  ANZSIC06 divisions A-S (excluding classes K633...  
...       ...                                                ...  
2013       52  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
2013       40  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
2013       12  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
2013        5  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
2013       46  ANZSIC06 groups C111, C112, C113, C114, C115, ...  

[37080 rows x 9 columns]

In [62]:
Data_new2[37075 :200000]

Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
Year                                                    
2013                     Level 3                 ZZ11   
2013                     Level 3                 ZZ11   
2013                     Level 3                 ZZ11   
2013                     Level 3                 ZZ11   
2013                     Level 3                 ZZ11   

            Industry_name_NZSIOC       Units Variable_code  \
Year                                                         
2013  Food product manufacturing  Percentage           H37   
2013  Food product manufacturing  Percentage           H38   
2013  Food product manufacturing  Percentage           H39   
2013  Food product manufacturing  Percentage           H40   
2013  Food product manufacturing  Percentage           H41   

                            Variable_name Variable_category Value  \
Year                                                                
2013                          Quick ratio  Financial ratios    52   
2013  Margin on sales of goods for resale  Financial ratios    40   
2013                     Return on equity  Financial ratios    12   
2013               Return on total assets  Financial ratios     5   
2013                Liabilities structure  Financial ratios    46   

                                 Industry_code_ANZSIC06  
Year                                                     
2013  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
2013  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
2013  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
2013  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
2013  ANZSIC06 groups C111, C112, C113, C114, C115, ...

In [63]:
dictionary  = { 'name' : ['Jack', 'Thomas', 'Alexandre'],
    'age' : [34, 30, 16],
    'city' : ['Paris', 'Roma', 'New York']}

df = pd.DataFrame(dictionary)
df

name  age      city
0       Jack   34     Paris
1     Thomas   30      Roma
2  Alexandre   16  New York

In [64]:
df.index=["Jack", "Thomas", "Alexandre"] 

In [65]:
df

name  age      city
Jack            Jack   34     Paris
Thomas        Thomas   30      Roma
Alexandre  Alexandre   16  New York

In [66]:
df.loc[["Jack", "Alexandre"]] 

name  age      city
Jack            Jack   34     Paris
Alexandre  Alexandre   16  New York

In [111]:
Data_new1 = pd.read_csv("Dataframe.csv")
print(Data_new1)
print(Data_new1.loc[[1,7]])
print("#####1######")
print(Data_new1.iloc[:,1:11:4])
print("#####2######")
print(Data_new1.iloc[3:5:,1:11:4])
print("#####3######")
print(Data_new1.iloc[3:5,[1,5,7]])
print("#####4######")
print(Data_new1.iloc[[1,6,7],[1,5,7]])
print("#####5######")
print(df)
print("#####6######")
print(df.iloc[[1,2],[2,1]])
print("#####7######")
print(df.loc[["Jack", "Alexandre"]])
print("#####8######")
print(df.loc[[]])


       Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2020                     Level 1                99999   
1      2020                     Level 1                99999   
2      2020                     Level 1                99999   
3      2020                     Level 1                99999   
4      2020                     Level 1                99999   
...     ...                         ...                  ...   
37075  2013                     Level 3                 ZZ11   
37076  2013                     Level 3                 ZZ11   
37077  2013                     Level 3                 ZZ11   
37078  2013                     Level 3                 ZZ11   
37079  2013                     Level 3                 ZZ11   

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01   
1                  All industries  Dollars (millions)           H04   
2                 

In [124]:
Data_new1 = pd.read_csv("Dataframe.csv")
print(Data_new1)
print("######")
Data_new2 = Data_new1.drop("Value",axis=1)
print(Data_new2)

       Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2020                     Level 1                99999   
1      2020                     Level 1                99999   
2      2020                     Level 1                99999   
3      2020                     Level 1                99999   
4      2020                     Level 1                99999   
...     ...                         ...                  ...   
37075  2013                     Level 3                 ZZ11   
37076  2013                     Level 3                 ZZ11   
37077  2013                     Level 3                 ZZ11   
37078  2013                     Level 3                 ZZ11   
37079  2013                     Level 3                 ZZ11   

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01   
1                  All industries  Dollars (millions)           H04   
2                 

In [125]:
dictionary  = { 'name' : ['Jack', 'Thomas', 'Alexandre'],
    'age' : [34, 30, 16],
    'city' : ['Paris', 'Roma', 'New York']}

df = pd.DataFrame(dictionary)
df

name  age      city
0       Jack   34     Paris
1     Thomas   30      Roma
2  Alexandre   16  New York

In [144]:
dic2 = { 'name' : ['Alex'],
    'age' : [15],
    'city' : ['Berlin']}
df2 = pd.DataFrame(dic2)
new_data5 = pd.concat([df,df2])
print(new_data5)
print(new_data5.loc[[0,1]])
print("####")
print(new_data5.iloc[[0],[1,2]])

        name  age      city
0       Jack   34     Paris
1     Thomas   30      Roma
2  Alexandre   16  New York
0       Alex   15    Berlin
     name  age    city
0    Jack   34   Paris
0    Alex   15  Berlin
1  Thomas   30    Roma
####
   age   city
0   34  Paris


In [146]:
import numpy as np
print(np.nan)

nan


In [150]:
# import pandas library
import pandas as pd
  
# dictionary with list object in values
details = {
    'Name' : ['Ankit', 'Aishwarya', 'Shaurya',
              'Shivangi', 'Priya', 'Swapnil'],
    'Age' : [23, 21, 22, 21, 24, 25],
    'University' : ['BHU', 'JNU', 'DU', 'BHU', 
                    'Geu', 'Geu'],
}
  
# creating a Dataframe object 
df = pd.DataFrame(details, columns = ['Name', 'Age',
                                      'University'],
                  index = ['a', 'b', 'c', 'd', 'e', 'f'])
print(df)
# get names of indexes for which
# column Age has value 21
index_names = df[ df['Age'] == 21 ].index
print(index_names)
# drop these row indexes
# from dataFrame
df.drop(index_names, inplace = True)
  
df

        Name  Age University
a      Ankit   23        BHU
b  Aishwarya   21        JNU
c    Shaurya   22         DU
d   Shivangi   21        BHU
e      Priya   24        Geu
f    Swapnil   25        Geu
Index(['b', 'd'], dtype='object')


Name  Age University
a    Ankit   23        BHU
c  Shaurya   22         DU
e    Priya   24        Geu
f  Swapnil   25        Geu

In [152]:
import pandas as pd
# used for np.nan
import numpy as np
# declared dictionary
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']} 
print(exam_data)
# DataFrame without using labels
Df = pd.DataFrame(exam_data)
print (Df)
# DataFrame using labels
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
Df.index = labels 
# another Methode Df = pd.DataFrame(exam_data,index =labels)
print(Df)
print ('#####################1################################')
# 1- Print the three first rows using head() method
print(Df.head(3))
print ('#####################2################################')
#Delete rows with Nan values
# index of Df['score'].isnull() == True
index_score = Df[ Df['score'].isnull() == True ].index
print(index_score)
# 2 -drop these row indexes from dataFrame
Df.drop(index_score, inplace = True)
print(Df)
print ('#####################3################################')
# 3- Extract the 'name' and 'score' columns from the DataFrame.
print(Df[['name','score']])
print ('#####################4################################')
#4- Write a Pandas program to append a new row 'k' to data frame with these values(name : "Suresh", score: 15.5, attempts: 1, qualify: "yes")
#exam_data = {'name': ['Anastasia'
exam_data2 = {'name' : "Suresh", 'score': 15.5, 'attempts': 1, 'qualify': "yes"}
print(exam_data2)
Df2 = pd.DataFrame(exam_data2,index =['k'])
New_Data= pd.concat([Df,Df2])
print(New_Data)
print ('#####################5################################')
# 5- Write a Pandas program to delete the 'attempts' column from the DataFrame.
New_Data1 =New_Data.drop('attempts',axis=1)
print(New_Data1)

{'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, nan, 9, 20, 14.5, nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
        name  score  attempts qualify
0  Anastasia   12.5         1     yes
1       Dima    9.0         3      no
2  Katherine   16.5         2     yes
3      James    NaN         3      no
4      Emily    9.0         2      no
5    Michael   20.0         3     yes
6    Matthew   14.5         1     yes
7      Laura    NaN         1      no
8      Kevin    8.0         2      no
9      Jonas   19.0         1     yes
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5       

In [153]:
New_Data1

name  score qualify
a  Anastasia   12.5     yes
b       Dima    9.0      no
c  Katherine   16.5     yes
e      Emily    9.0      no
f    Michael   20.0     yes
g    Matthew   14.5     yes
i      Kevin    8.0      no
j      Jonas   19.0     yes
k     Suresh   15.5     yes

In [165]:
New_Data1['Total_Score'] = New_Data1.apply(lambda row: str(row.name) + str(row.score), axis = 1) 

def funcl(a):
    if a>= 10.0:
        return 1
    else:
        return 0

#New_Data1['Total_Score2'] = New_Data1.apply(lambda row.score:  funcl  , axis = 1) 
New_Data1['Total_Score2'] = New_Data1.apply(lambda row:  funcl(row.score)  , axis = 1) 
New_Data1

name  score qualify Total_Score  Total_Score2
a  Anastasia   12.5     yes       a12.5             1
b       Dima    9.0      no        b9.0             0
c  Katherine   16.5     yes       c16.5             1
e      Emily    9.0      no        e9.0             0
f    Michael   20.0     yes       f20.0             1
g    Matthew   14.5     yes       g14.5             1
i      Kevin    8.0      no        i8.0             0
j      Jonas   19.0     yes       j19.0             1
k     Suresh   15.5     yes       k15.5             1